YC 1145 classifier nn
softmatterlab/Braph-2.0-Matlab pull request #1147
Opened 2022-01-12 16:04 UTC by c-yuwei

2022-01-25 00:01 UTC, c-yuwei commented
24/1 - working version, need to polish the comments and typos

2022-01-25 00:07 UTC, c-yuwei commented on braph2genesis/neuralnetworks/_NNClassifierDNN.gen.m
> +0
should be false

2022-01-25 00:08 UTC, c-yuwei commented on braph2genesis/neuralnetworks/_NNClassifierDNN.gen.m
> +SHUFFLE (data, OPTION) is a option for data shuffling.
"an'' option

2022-01-25 00:08 UTC, c-yuwei commented on braph2genesis/neuralnetworks/_NNClassifierDNN.gen.m
> +    options = trainingOptions('adam', ...
make "adam" as a property

2022-01-25 00:09 UTC, c-yuwei commented on braph2genesis/neuralnetworks/_NNClassifierData.gen.m
> +GIVEN_FEATURE_MASK (data, cell) is a mask for selected features.
is a "given" mask for ...

2022-01-25 00:09 UTC, c-yuwei commented on braph2genesis/neuralnetworks/_NNClassifierData.gen.m
> +CALCULATED_FEATURE_MASK (result, cell) is a mask for selected features.
is a mask "generated with the training data" for ...

2022-01-25 08:56 UTC, c-yuwei commented on braph2genesis/neuralnetworks/_NNClassifierData.gen.m
> +%%%% ¡conditioning!
use [2 3] instead of [0 1 1 0 0 ...]

2022-01-25 08:56 UTC, c-yuwei commented on braph2genesis/neuralnetworks/_NNClassifierData.gen.m
> +TRAIN_VAL_INDEX_GR_1 (data, rvector) is a vector sepcify which subject in group 1 goes to validation set. It can also be a scalar that represents the proportion of the dataset to include in the test
typo

2022-01-25 08:56 UTC, c-yuwei commented on braph2genesis/neuralnetworks/_NNClassifierData.gen.m
> +    num_val = value*nnd.get('GR_2').get('SUB_DICT').length();
formatting

2022-01-26 07:26 UTC, giovannivolpe requested changes

2022-01-26 07:26 UTC, giovannivolpe commented on braph2genesis/neuralnetworks/_NNClassifierData.gen.m
> +Use one of its subclasses instead.
describe data mor ein detail

2022-01-26 07:26 UTC, giovannivolpe commented on braph2genesis/neuralnetworks/_NNClassifierData.gen.m
> +
remove

2022-01-26 07:26 UTC, giovannivolpe commented on braph2genesis/neuralnetworks/_NNClassifierData.gen.m
> +    num_val = value * nnd.get('GR_2').get('SUB_DICT').length();
floor

2022-01-26 07:26 UTC, giovannivolpe commented on braph2genesis/neuralnetworks/_NNClassifierData.gen.m
> +if isa(value, 'double')
check that it's a single double

2022-01-26 07:26 UTC, giovannivolpe commented on braph2genesis/neuralnetworks/_NNClassifierData.gen.m
> +value = {idx_all(1:num_top_idx)};
use single property like in groups divisors

2022-01-26 07:26 UTC, giovannivolpe commented on braph2genesis/neuralnetworks/_NNClassifierData.gen.m
> +
remove

2022-01-26 07:26 UTC, giovannivolpe commented on braph2genesis/neuralnetworks/_NNClassifierData.gen.m
> +    xmax = max(X,[],2);
spaces

2022-01-26 09:56 UTC, c-yuwei commented on braph2genesis/pipelines/connectivity neural_network_analysis/example_CON_NN_WU.m
> +nn_CON.performKFoldCrossValidation('ConfusionMatrix');
outdated, the cross-validation will be integrated in another branch.

2022-01-26 09:57 UTC, c-yuwei commented on braph2genesis/pipelines/connectivity neural_network_analysis/example_CON_NN_WU.m
> +    'DENSITY_OF_FEATURE_SELECTION', 0.05);
outdated

2022-01-26 09:57 UTC, c-yuwei commented on braph2genesis/pipelines/connectivity neural_network_analysis/example_CON_NN_WU.m
> +nn_CON.performNeuralNetworkPrediction('ConfusionMatrix', a_WU1_test, a_WU2_test);
outdated

2022-01-26 10:01 UTC, c-yuwei commented on braph2genesis/src/nn/_NNBase.gen.m
> +DATA (data, item)
done, 0b2b6f40cf68a27ee3208fdffdf02101ad989927

2022-01-26 10:04 UTC, c-yuwei commented on braph2genesis/src/nn/_NNBase.gen.m
> +
d219c838bbb708561ed5ead3843f1790783409a9

2022-01-26 10:11 UTC, c-yuwei commented on braph2genesis/src/nn/_NNBase.gen.m
> +    % to a string format that can be saved as cell in braph.
done, ed2d25824d4e276917d90ebf9d3b1963818ebce6

2022-01-26 10:11 UTC, c-yuwei commented on braph2genesis/src/nn/_NNBase.gen.m
> +
done, ed2d25824d4e276917d90ebf9d3b1963818ebce6

2022-01-26 10:12 UTC, c-yuwei commented on braph2genesis/src/nn/_NNBase.gen.m
> +
done, ed2d25824d4e276917d90ebf9d3b1963818ebce6

2022-01-26 10:12 UTC, c-yuwei commented on braph2genesis/src/nn/_NNBase.gen.m
> +    % in braph to a build-in object in matlab.
done, ed2d25824d4e276917d90ebf9d3b1963818ebce6

2022-01-26 10:20 UTC, c-yuwei commented on braph2genesis/src/nn/_NNBase.gen.m
> +    warning('off', 'MATLAB:mir_warning_unrecognized_pragma')
0853aae3cd90ff396a26765af07d61b508995c61

2022-01-26 10:23 UTC, c-yuwei commented on braph2genesis/src/nn/_NNEvaluator.gen.m
> +
391a816df7d605bee8397ec82c0a6f920ae61189

2022-01-26 10:23 UTC, c-yuwei commented on braph2genesis/src/nn/_NNEvaluator.gen.m
> +NN_DATA (data, item) is a dataset for neural networks.
391a816df7d605bee8397ec82c0a6f920ae61189

2022-01-26 10:23 UTC, c-yuwei commented on braph2genesis/src/nn/_NNEvaluator.gen.m
> +NN_MODEL (data, item) is a neural network that need to be evaluated.
391a816df7d605bee8397ec82c0a6f920ae61189

2022-01-26 10:23 UTC, c-yuwei commented on braph2genesis/src/nn/_NNEvaluator.gen.m
> +NN_VAL_PREDICTION (result, matrix) is the predictions from a neural network for validation set.
391a816df7d605bee8397ec82c0a6f920ae61189

2022-01-26 11:09 UTC, c-yuwei commented on braph2genesis/neuralnetworks/_NNClassifierDNN.gen.m
> +NNClassifierData (data, item) is a dataset for training or testing a neural network classifier.
f5fb0dd0d8f819b254c05b7d40565d50dbc85bbc

2022-01-26 11:09 UTC, c-yuwei commented on braph2genesis/neuralnetworks/_NNClassifierDNN.gen.m
> +MINI_BATCH_SIZE (data, scalar) is the size of the mini-batch to use for each training iteration.
f5fb0dd0d8f819b254c05b7d40565d50dbc85bbc

2022-01-26 11:09 UTC, c-yuwei commented on braph2genesis/neuralnetworks/_NNClassifierDNN.gen.m
> +%%%% ¡default!
f5fb0dd0d8f819b254c05b7d40565d50dbc85bbc

2022-01-26 11:09 UTC, c-yuwei commented on braph2genesis/neuralnetworks/_NNClassifierDNN.gen.m
> +'once'
f5fb0dd0d8f819b254c05b7d40565d50dbc85bbc

2022-01-26 11:10 UTC, c-yuwei commented on braph2genesis/neuralnetworks/_NNClassifierDNN.gen.m
> +{'sgdm' 'rmsprop' 'adam'}
f5fb0dd0d8f819b254c05b7d40565d50dbc85bbc

2022-01-26 11:10 UTC, c-yuwei commented on braph2genesis/neuralnetworks/_NNClassifierDNN.gen.m
> +'none'
f5fb0dd0d8f819b254c05b7d40565d50dbc85bbc

2022-01-26 11:10 UTC, c-yuwei commented on braph2genesis/neuralnetworks/_NNClassifierDNN.gen.m
> +false
f5fb0dd0d8f819b254c05b7d40565d50dbc85bbc

2022-01-26 11:10 UTC, c-yuwei commented on braph2genesis/neuralnetworks/_NNClassifierDNN.gen.m
> +TRAINED_NN (result, cell) is a trained neural network classifier.
f5fb0dd0d8f819b254c05b7d40565d50dbc85bbc

2022-01-26 14:31 UTC, c-yuwei commented on braph2genesis/neuralnetworks/_NNClassifierData.gen.m
> +if isa(value, 'double')
fb6c8a899ad7ebb0d8d504b778f157d9360ff892

2022-01-26 14:31 UTC, c-yuwei commented on braph2genesis/neuralnetworks/_NNClassifierData.gen.m
> +    num_val = value * nnd.get('GR_2').get('SUB_DICT').length();
fb6c8a899ad7ebb0d8d504b778f157d9360ff892

2022-01-26 14:40 UTC, c-yuwei commented on braph2genesis/neuralnetworks/_NNClassifierData.gen.m
> +value = {idx_all(1:num_top_idx)};
e283b7398513eca7d5e2e8607c3f2340e6974fa4

2022-01-26 14:42 UTC, c-yuwei commented on braph2genesis/neuralnetworks/_NNClassifierData.gen.m
> +    xmax = max(X,[],2);
3c3a43b22f65ab7878bd152992390965a7ec32b7

2022-01-26 14:42 UTC, c-yuwei commented on braph2genesis/neuralnetworks/_NNClassifierData.gen.m
> +
47884cf3b92b8152fa3e1d49c229a1f29d229722

2022-01-26 14:45 UTC, c-yuwei commented on braph2genesis/src/nn/_NNBase.gen.m
> +
537092be96bcc68a813fd0c830c34a814088d43a

2022-01-26 17:59 UTC, c-yuwei commented on braph2genesis/neuralnetworks/_NNClassifierDNN.gen.m
> +
a30b64051fcb6203d4527bebed7f369c6f59bda6

2022-01-26 18:02 UTC, c-yuwei commented on braph2genesis/neuralnetworks/_NNClassifierData.gen.m
> +
5c7fd21ff03f3b1182ad419beff405e0764446e5

2022-01-26 18:02 UTC, c-yuwei commented on braph2genesis/neuralnetworks/_NNClassifierData.gen.m
> +[]
5c7fd21ff03f3b1182ad419beff405e0764446e5

2022-01-26 19:17 UTC, c-yuwei commented on braph2genesis/src/nn/_NNBase.gen.m
> +    lgraph = importONNXLayers(filename, InputDataFormats = "BCSS");
7347640c74696cba442524db61af0ec59087312c

2022-01-26 19:33 UTC, c-yuwei commented on braph2genesis/neuralnetworks/_NNClassifierData.gen.m
> +Use one of its subclasses instead.
c800deba2854ebe2054c763bec32440a41d843dc

2022-01-26 19:33 UTC, c-yuwei commented on braph2genesis/neuralnetworks/_NNClassifierDNN.gen.m
> +
c800deba2854ebe2054c763bec32440a41d843dc

2022-01-26 20:03 UTC, c-yuwei commented
2bb0bb227307278c926edc42a8fbaa83c9c13250 is the working version for example_CON_NN_WU.
All demands have been sorted, and two things should be noted:

1. the feature mask now is a metadata rather than a data or parameter (see _NNClassifierData.gen.m )
In order to set the value for the feature mask with conditioning or postprocessing, it has to be metadata, so the value can be set during the process. The thing is that, when determining the value of the mask, it will start to get the result of the object itself, so the property (either data or parameter) will be locked. 

2. to_net and from_net now is working properly.
Instead of rewriting them in each subclass, now it passes the varargin to the method in the superclass NNBase.

2022-02-09 17:54 UTC, c-yuwei commented
<img width="542" alt="image" src="https://user-images.githubusercontent.com/30530538/153260617-38d5a4ca-38ed-4f71-89a5-439618f55709.png">
I cannot narrow the classlist to one certain type, e.g., Measure and its subclass

2022-02-14 20:22 UTC, merged