figure titles
softmatterlab/Braph-2.0-Matlab pull request #1208
Opened 2022-02-28 16:28 UTC by egolol

2022-03-01 15:50 UTC, annacanal requested changes
After comparing a nodal measure, like Degree, I press to show comparison and an error jumps:

```
Brace indexing is not supported for variables of this type.

Error in PPComparisonGroup_Diff/update (line 954)
		                full_value{k, 2} = p1{k};

Error in PlotElement/update (line 1127)
		        pe.get('PR_DICT').getItem(prop).update()

Error in PlotElement/draw (line 1107)
		    pe.update()

Error in GUI/draw (line 1216)
		    pe.draw('Parent', gui.pp)

Error in PPCompareGroup_CPDict_WU/cb_measure_gui (line 968)
		                    pr.f_m{f_count} = GUI('pe', cp, 'POSITION', [x y w h], 'CLOSEREQ', false).draw();

Error in PPCompareGroup_CPDict_WU/draw/cb_measure_plot_btn (line 775)
		        pr.cb_measure_gui();
 
Error while evaluating UIControl Callback.
```

Moreover, titles of figures appear on atlas, but not on measure results figure 

atlas correct:
![atlas_figure_titles_good](https://user-images.githubusercontent.com/31701548/156201615-346e9d49-a32e-4b2e-a12a-f60b1135f29f.png)

analysis no title:
![measure_degree_plot_notitlename](https://user-images.githubusercontent.com/31701548/156201663-37f4bf5b-870b-4062-8a4c-233cb3ff5055.png)

2022-03-01 16:16 UTC, annacanal commented
Rearrangement of diff, p1, p2 and ciu and cil works, now everything on the same table, but it is under the same title DIFF, and then we still have individually p2, p1...etc
![Screenshot 2022-03-01 at 17 11 13](https://user-images.githubusercontent.com/31701548/156206167-59684b5f-07fc-42ff-94ee-19e4a2bdd7c3.png)

2022-03-01 22:40 UTC, annacanal commented
In general, all the issues supposed to be fixed in this branch are fixed.
Except for:
1. adding **titles** on all **figures**, **plot brain view** from **analysis** or **comparison** is missing:
<img width="1125" alt="Screenshot 2022-03-01 at 23 33 23" src="https://user-images.githubusercontent.com/31701548/156260414-d50e1c1f-34ee-4fcc-8cef-808247a00949.png">

 2. Mismatch for line width and marker width: **marker width does not work yet**, does not update size by its own in any of the plots from analysis or comparison of structural BUD


3. From the comparison, when pressing the buttons to add CIU and CIL on the plot across densities, these errors jump:

```
Output argument "limit" (and maybe others) not assigned during call to "PlotComparisonGroupLine.settings/obtain_cil_ciu_value".

Error in PlotComparisonGroupLine/settings/cb_show_confidence_interval_min (line 1338)
		                cil = obtain_cil_ciu_value(pr.get('CIL'));
 
Error while evaluating UIControl Callback.
```
```
Output argument "limit" (and maybe others) not assigned during call to "PlotComparisonGroupLine.settings/obtain_cil_ciu_value".

Error in PlotComparisonGroupLine/settings/cb_show_confidence_interval_max (line 1360)
		                ciu = obtain_cil_ciu_value(pr.get('CIU'));
 
Error while evaluating UIControl Callback.
```

2022-03-02 13:58 UTC, annacanal approved these changes

2022-03-02 14:11 UTC, annacanal commented
All subissues meant to be solved in this branch have been tested. 
Some extra things detected are being taken care of by @egolol in a new branch (#1211 ). So this branch can be merged into gv_final

2022-03-03 07:41 UTC, giovannivolpe requested changes
* Substitute Inner_Show and Inner_Hide with cb_bring_to_front and cb_hide (change also in Plot)

2022-03-03 07:59 UTC, giovannivolpe requested changes

2022-03-03 07:59 UTC, giovannivolpe commented on braph2genesis/src/cohort/_PPSubject_ID.gen.m
> -    update_btn = get(figure_h, 'UserData');
do this with a callback function

2022-03-04 14:09 UTC, giovannivolpe requested changes

2022-03-04 14:09 UTC, giovannivolpe commented on braph2genesis/pipelines/structural multiplex/_PPAnalyzeGroupMP_G.gen.m
> +    if isempty(pr.f_g) || ~check_graphics(pr.f_g, 'figure')
use only check_graphics

2022-03-04 14:09 UTC, giovannivolpe commented on braph2genesis/pipelines/structural multiplex/_PPAnalyzeGroupMP_G.gen.m
> +            if isgraphics(tmp_f)
use check_graphics

2022-03-04 14:09 UTC, giovannivolpe commented on braph2genesis/src/analysis/_PPComparisonGroup_Diff.gen.m
> +            'String', [label ': ' slider_tags{round(get(pr.slider, 'Value'))* map_multiplier}]);
space

2022-03-04 14:09 UTC, giovannivolpe commented on braph2genesis/src/analysis/_PPComparisonGroup_Diff.gen.m
> +            'String', ['Layer: ' num2str(round(get(pr.second_slider, 'Value'))* map_multiplier)]);
space

2022-03-04 14:09 UTC, giovannivolpe commented on braph2genesis/src/analysis/_PPComparisonGroup_Diff.gen.m
> +        'SliderStep', [map_multiplier/(L*map_multiplier) map_multiplier/(L*map_multiplier)] , ...
spaces

2022-03-04 14:09 UTC, giovannivolpe commented on braph2genesis/src/analysis/_PPComparisonGroup_Diff.gen.m
> +            'SliderStep', [map_multiplier/(L2*map_multiplier) map_multiplier/(L2*map_multiplier)] , ...
spaces

2022-03-04 14:09 UTC, giovannivolpe commented on braph2genesis/src/atlas/_PlotBrainAtlas.gen.m
> +    pl.cb_bring_to_front@Plot();
comment

2022-03-04 16:45 UTC, giovannivolpe approved these changes

2022-03-04 16:45 UTC, merged