yc-postprocessing-for-covariates
softmatterlab/Braph-2.0-Matlab pull request #1213
Opened 2022-03-02 21:31 UTC by c-yuwei

This pull request will solve the conditional usage for USE_COVARIATES and CORRELATION_RULE by postprocessing the functionality.

When the USE_COVARIATES is checked, only partial Pearson and partial Spearman are available.
When the USE_COVARIATES is unchecked, only Pearson, Spearman, and Kendall are available.

See testing video:
https://user-images.githubusercontent.com/30530538/156452885-2efacf82-5b5c-41c9-8967-109df1ca7162.mp4

2022-03-03 07:16 UTC, giovannivolpe requested changes
* Use only one field (Pearson/Spearman with convariates instead of partial).
* Remove PPs
* Check Correlation and its docs

2022-03-03 20:23 UTC, c-yuwei commented
- Removed "USE_COVARIATES" in all related files with the following pipelines
ST, BUD, BUT, MP_ST, MP_BUD, and MP_BUT
- Tested with all abovementioned pipelines.

2022-03-04 12:13 UTC, giovannivolpe requested changes

2022-03-04 12:13 UTC, giovannivolpe commented on braph2genesis/src/analysis/Correlation.m
> +    %  Correlation_Rule_List        - Pearson, Spearman, Kendall, Pearson
capital

2022-03-04 12:13 UTC, giovannivolpe commented on braph2genesis/src/analysis/Correlation.m
> +        CORRELATION_RULE_LIST = {'Pearson', 'Spearman', 'Kendall', 'Pearson with covariates', 'Spearman with covariates'};
PEARSON = 'Pearson';
SPEARMAN = 'Spearman';
... 'Kendall'
PEARSON_CV = 'Pearson with covariates'
'Spearman with covariates'
CORRELATION_RULE_LIST = {Correlation.PEARSON ...};

2022-03-04 12:13 UTC, giovannivolpe commented on braph2genesis/src/analysis/Correlation.m
>                  case 'kendall'
case Correlation.KENDALL ...

2022-03-04 12:13 UTC, giovannivolpe commented on braph2genesis/pipelines/structural/example_ST_WU.m
> +a_WU1 = AnalyzeGroup_ST_WU('GR', gr1, 'CORRELATION_RULE', 'Pearson with covariates');
change

2022-03-04 12:13 UTC, giovannivolpe commented on braph2genesis/pipelines/structural/_AnalyzeGroup_ST_WU.gen.m
> +if any(strcmp(a.get('CORRELATION_RULE'), {'Pearson with covariates', 'Spearman with covariates'}))
change

2022-03-04 22:40 UTC, c-yuwei commented on braph2genesis/pipelines/structural/_AnalyzeGroup_ST_WU.gen.m
> +if any(strcmp(a.get('CORRELATION_RULE'), {'Pearson with covariates', 'Spearman with covariates'}))
done

2022-03-04 22:40 UTC, c-yuwei commented on braph2genesis/pipelines/structural/example_ST_WU.m
> +a_WU1 = AnalyzeGroup_ST_WU('GR', gr1, 'CORRELATION_RULE', 'Pearson with covariates');
done

2022-03-04 22:40 UTC, c-yuwei commented on braph2genesis/src/analysis/Correlation.m
>                  case 'kendall'
done

2022-03-04 22:40 UTC, c-yuwei commented on braph2genesis/src/analysis/Correlation.m
> +        CORRELATION_RULE_LIST = {'Pearson', 'Spearman', 'Kendall', 'Pearson with covariates', 'Spearman with covariates'};
done

2022-03-04 22:40 UTC, c-yuwei commented on braph2genesis/src/analysis/Correlation.m
> +    %  Correlation_Rule_List        - Pearson, Spearman, Kendall, Pearson
done

2022-03-05 03:13 UTC, giovannivolpe approved these changes

2022-03-05 03:16 UTC, giovannivolpe approved these changes

2022-03-05 03:19 UTC, merged