Fundamental changes for NN framework
softmatterlab/Braph-2.0-Matlab pull request #1231
Opened 2022-03-16 01:17 UTC by c-yuwei

This PR improves the generalizability of NN framework, making the pipelines more flexible to various types of input data (e.g., graph measures, adj matrix, multiplex, multigraph). 
The main implementation is introducing NNGroup and NNSubject to coordinate the input and output for NN.
By doing so, any input from ST, CON, FUN, multigraph, or multiplex can be altered and adapted to desired NN model.

2022-03-18 07:17 UTC, c-yuwei commented on braph2genesis/src/nn/_NNGroup.gen.m
> +Group provides the methods necessary to handle groups of subjects.
describe here what is the feature mask

2022-03-18 07:53 UTC, giovannivolpe requested changes

2022-03-18 07:53 UTC, giovannivolpe commented on braph2genesis/src/nn/_NNGroup.gen.m
> +FEATURE_MASK (metadata, cell) is an feature mask for all the NN subjects in the group.
these should be data

2022-03-18 07:53 UTC, giovannivolpe commented on braph2genesis/src/nn/_NNSubject.gen.m
> +% % pr = PPSubjectCON_CON('EL', sub, 'PROP', SubjectCON.CON, varargin{:});
propos: input (data), mask (data), input_masked (result)

2022-03-18 07:53 UTC, giovannivolpe commented on braph2genesis/src/nn/_NNGroup.gen.m
> +FEATURE_MASK (metadata, cell) is an feature mask for all the NN subjects in the group.
no mask, but inputs and inputs_masked as results that collect the data from subjects

2022-03-18 07:53 UTC, giovannivolpe commented on braph2genesis/src/nn/_NNSubject.gen.m
> +INPUT (data, cell) is the input obtained from the data of subject for the neural network analysis.
make it into cell as we discussed

2022-03-18 07:53 UTC, giovannivolpe commented on braph2genesis/src/nn/_NNSubject.gen.m
> +TARGET (data, string) is the target of the subject for the neural network analysis.
cell

2022-03-19 15:43 UTC, c-yuwei commented
The following elements have been tested:
- [x] 'test_NNBase'
- [x] 'test_NNData'
- [x] 'test_NNEvaluator'
- [x] 'test_NNGroup'
- [x] 'test_NNSubject'
- [x] 'test_NNClassifierData'
- [x] 'test_NNClassifierEvaluator'
- [x] 'test_NNClassifierDNN'
- [x] 'test_NNClassifierData_CON_WU'

2022-03-20 11:17 UTC, merged