GUIAnalysis
softmatterlab/Braph-2.0-Matlab pull request #623
Opened 2020-08-13 14:19 UTC by egolol

first commmit, works until tab

2020-08-24 12:29 UTC, egolol commented on braph2/workflows/Structural/AnalysisST_BUD.m
> +    %  getMainPanelMeasurePlot      - creates a uipanel for a plot
I will put the nodal and binodal in another branch

2020-08-25 14:21 UTC, giovannivolpe requested changes

2020-08-25 14:21 UTC, giovannivolpe commented on braph2/analysis/Comparison.m
> +    %  getChildPanel            - returns a dynamic UIPanel
remove

2020-08-25 14:21 UTC, giovannivolpe commented on braph2/analysis/Comparison.m
> +        function GUIComparison(comparison_class, analysis)
Move it as a separate function in separate file

2020-08-25 14:21 UTC, giovannivolpe commented on braph2/analysis/Measurement.m
> +    %  getChildPanel            - returns a dynamic UIPanel
remove method childPanel

2020-08-25 14:21 UTC, giovannivolpe commented on braph2/analysis/Measurement.m
> +        function GUIMeasurement(measurement_class, analysis)
separate file

2020-08-25 14:21 UTC, giovannivolpe commented on braph2/analysis/RandomComparison.m
> +    %  getChildPanel            - returns a dynamic UIPanel
Rrmove

2020-08-25 14:21 UTC, giovannivolpe commented on braph2/analysis/RandomComparison.m
> +        function GUIRandomComparison(comparison_class, analysis)
Separate file

2020-08-28 15:11 UTC, merged