630 ac adapt richness
softmatterlab/Braph-2.0-Matlab pull request #631
Opened 2020-08-26 14:42 UTC by annacanal

- Adapt richness measure for parametric format
- No need to change test_Measure

2020-08-26 16:02 UTC, giovannivolpe requested changes
1. Add comments in measure
2. Add methods to get info on name of parameter and its values
3. Correct errors in test functions (we need to discuss this before making changes)

2020-08-26 21:46 UTC, annacanal commented
> 1. Add comments in measure
> 2. Add methods to get info on name of parameter and its values
> 3. Correct errors in test functions (we need to discuss this before making changes)

1 and 2 done. Will check the errors tomorrow morning

2020-08-28 07:06 UTC, giovannivolpe commented on braph2/workflows/Structural/ComparisonST_WU.m
> +                    all(cellfun(@(x) isequal(size(x, 1), 1), c.getGroupValue(1))) &&...
add space between && and ...
(also below)

2020-08-28 10:54 UTC, annacanal commented on braph2/workflows/Structural/ComparisonST_WU.m
> +                    all(cellfun(@(x) isequal(size(x, 1), 1), c.getGroupValue(1))) &&...
done everywhere

2020-08-28 10:55 UTC, annacanal commented on braph2/graph/measures/Richness.m
> +                values = k_level; % will gives errors to negative thresholds now
solved

2020-08-28 14:32 UTC, giovannivolpe requested changes
1) correct sizes of defaults
2) check also 3rd dimension

2020-08-28 14:32 UTC, giovannivolpe commented on braph2/workflows/Structural/MeasurementST_WU.m
> +                    {1}, ...  % 1 dimension minimum
[]

2020-08-31 14:19 UTC, giovannivolpe requested changes
Manage parameter values also in ComparisonST and RandomComparisonST as in MeasurementST

2020-08-31 17:04 UTC, giovannivolpe requested changes
small things

2020-08-31 17:04 UTC, giovannivolpe commented on braph2/workflows/Structural/ComparisonST_WU.m
> +        function parameter_values = getParameterValues(c)
call it getMeasureParameterValues

2020-08-31 17:04 UTC, giovannivolpe commented on braph2/workflows/Structural/RandomComparisonST_WU.m
> +        function parameter_values = getParameterValues(rc)
call it getMeasureParameterValues

2020-08-31 17:04 UTC, giovannivolpe commented on braph2/workflows/Structural/AnalysisST_WU.m
> +            %send the variables
Is this done?

2020-08-31 17:04 UTC, giovannivolpe commented on braph2/workflows/Structural/AnalysisST_WU.m
> +                'RandomComparisonST.ParameterValuesLength', parameter_values_length, ...
should not exist

2020-08-31 17:04 UTC, giovannivolpe commented on braph2/workflows/Structural/AnalysisST_WU.m
> +                'ComparisonST.ParameterValuesLength', parameter_values_length1, ...
should not exist

2020-08-31 17:07 UTC, annacanal commented on braph2/workflows/Structural/AnalysisST_WU.m
> +            %send the variables
yes

2020-09-01 13:38 UTC, giovannivolpe approved these changes

2020-09-01 13:41 UTC, merged