Updated StructuralMultiplex Measurement
softmatterlab/Braph-2.0-Matlab pull request #650
Opened 2020-09-07 08:11 UTC by annacanal

2020-09-11 07:59 UTC, egolol requested changes
I think you should return empty for all guis, and then work on them. For the core, I think seems ok.

2020-09-11 07:59 UTC, egolol commented on braph2/workflows/StructuralMultiplex/AnalysisST_MP_BUD.m
> +            if ~isempty(X) && ~isempty(Y)
I think this will not work. Since you have also layers to choose from.

2020-09-11 07:59 UTC, egolol commented on braph2/workflows/StructuralMultiplex/AnalysisST_MP_WU.m
> +            for i = 1:1:subject_number
does this only work for 2 layers?

2020-09-11 07:59 UTC, egolol commented on braph2/workflows/StructuralMultiplex/AnalysisST_MP_WU.m
> +                    group = analysis.getCohort().getGroups().getValue(selected_group);
this will not work

2020-09-11 08:40 UTC, annacanal commented on braph2/workflows/StructuralMultiplex/AnalysisST_MP_WU.m
> +            for i = 1:1:subject_number
yes. 2 layers. it is on the description of analysis

2020-09-11 08:44 UTC, annacanal commented on braph2/workflows/StructuralMultiplex/AnalysisST_MP_WU.m
> +                    group = analysis.getCohort().getGroups().getValue(selected_group);
no. I havent check/adapt any plot function yet

2020-09-11 08:47 UTC, annacanal commented on braph2/workflows/StructuralMultiplex/AnalysisST_MP_BUD.m
> +            if ~isempty(X) && ~isempty(Y)
well, it will depend on the measure.. if it is superglobal, then is 1 output for all layers. If it is unilayer, then one layer should be chosen. If it is bilayer (any measure yet), between which layers should be chosen.

But as said, I haven't check all of the graphical parts. 
I can leave it empty so far

2020-09-15 11:50 UTC, giovannivolpe approved these changes

2020-09-15 11:50 UTC, merged