update
softmatterlab/Braph-2.0-Matlab pull request #660
Opened 2020-09-09 15:40 UTC by egolol

should be more general

2020-09-10 07:56 UTC, annacanal approved these changes

2020-09-11 14:11 UTC, giovannivolpe requested changes
revert to name "desikan_atlas"

2020-09-11 14:13 UTC, giovannivolpe requested changes
revert to "desikan_atlas"

2020-09-15 11:57 UTC, giovannivolpe approved these changes

2020-09-15 11:57 UTC, merged