update fdr
softmatterlab/Braph-2.0-Matlab pull request #661
Opened 2020-09-10 14:45 UTC by egolol

2020-09-11 14:23 UTC, giovannivolpe requested changes

2020-09-11 14:23 UTC, giovannivolpe commented on braph2/util/IndexedDictionary.m
> +            elseif isequal(pointer.getClass(), idict.getValueClass())  % pointer is a value
change to isa(pointer, idict.getValueClass())
and verify that all works.

2020-09-11 14:23 UTC, giovannivolpe commented on braph2/workflows/Structural/AnalysisST_WU.m
> +            difference_mean = cellfun(@(x, y) y - x, value_1, value_2, 'UniformOutput', false);
Is this change because of the comparison order we discussed with Anna?

2020-09-14 08:30 UTC, egolol commented on braph2/workflows/Structural/AnalysisST_WU.m
> +            difference_mean = cellfun(@(x, y) y - x, value_1, value_2, 'UniformOutput', false);
yes

2020-09-15 11:54 UTC, giovannivolpe approved these changes

2020-09-15 11:59 UTC, merged