correction
softmatterlab/Braph-2.0-Matlab pull request #691
Opened 2020-09-24 09:27 UTC by egolol

2020-09-24 17:44 UTC, annacanal approved these changes

2020-09-25 16:57 UTC, giovannivolpe requested changes
The default p-value should be 1, not 0.05, because we don't what it significant if the differences are zero.

I think the second check should not be "length(current_random_differences) > 0", but something to double-check that all values in current_random_differences are zero.

2020-09-25 16:57 UTC, giovannivolpe commented on braph2/analysis/pvalue2.m
> +                        P2(i, j, t) = 0.05; %#ok<AGROW>
this should be 1

2020-09-25 16:57 UTC, giovannivolpe commented on braph2/analysis/pvalue1.m
> +                        P1(i, j, t) =  0.05;                             %#ok<AGROW>
this should be 1

2020-09-25 16:57 UTC, giovannivolpe commented on braph2/analysis/pvalue2.m
> +                    if current_observed_difference == 0 && length(current_random_differences) > 0  %#ok<ISMT>
why do you need the check "&& length(current_random_differences) > 0"?

2020-09-25 16:57 UTC, giovannivolpe commented on braph2/analysis/pvalue1.m
> +                    elseif current_observed_difference == 0  && length(current_random_differences) > 0 %#ok<ISMT>
why do you need the check "&& length(current_random_differences) > 0"?

2020-09-25 17:12 UTC, giovannivolpe commented
@egolol @annacanal @mitemijalkov Also, please add some unit tests to check that when the two distributions are the same the pvalues are not significative.

2020-09-25 18:57 UTC, giovannivolpe requested changes

2020-09-25 18:57 UTC, giovannivolpe commented on braph2/analysis/pvalue1.m
>                      end
add if pvalue == 0, make it 1/number premutations

2020-09-25 18:57 UTC, giovannivolpe commented on braph2/analysis/pvalue2.m
>                  end
add if pvalue == 0, make it 1/number premutations

2020-09-29 08:57 UTC, egolol commented on braph2/analysis/pvalue1.m
>                      end
I dont understand this instruction. Is it : 

1.  if P1(i, j, t) = 0   then P1(i,j,t) = 1/ # permutations end

2. P1(i,j,t) = (length(find(current_random_differences < current_observed_difference))) ...
                            / ...
                            length(random_differences);

2020-09-29 13:31 UTC, annacanal commented on braph2/analysis/pvalue1.m
>                      end
Yes, I understand it like this. well, 2 before 1.

2020-09-29 13:51 UTC, closed without merging