710-yc-Diameter
softmatterlab/Braph-2.0-Matlab pull request #723
Opened 2020-11-01 22:40 UTC by maverickyuwei

Initiation.

2020-11-13 17:18 UTC, maverickyuwei commented
- [x] Diameter
- [ ] test_Diameter

2020-11-20 09:13 UTC, annacanal requested changes

2020-11-20 09:13 UTC, annacanal commented on braph2/graph/measures/Diameter.m
> +                eccentricity = g.getMeasure('Eccentricity').getValue();
Instead: eccentricity = g.getMeasureValue('Eccentricity');

2020-11-20 09:13 UTC, annacanal commented on braph2/graph/measures/test_Diameter.m
> +known_diameter_subgraphs = {[1]};
known_diameter_subgraphs = {1};

2020-11-20 09:13 UTC, annacanal commented on braph2/graph/measures/test_Diameter.m
> +known_diameter_default = {[Inf]'};
known_diameter_default = {Inf};

2020-11-20 09:13 UTC, annacanal commented on braph2/graph/measures/test_Diameter.m
> +known_diameter_subgraphs = {[5]};
known_diameter_subgraphs = {5};

2020-11-20 09:13 UTC, annacanal commented on braph2/graph/measures/test_Diameter.m
> +known_diameter_default = {[Inf]};
known_diameter_default = {Inf};

2020-11-20 09:13 UTC, annacanal commented on braph2/graph/measures/test_Diameter.m
> +
known_diameter_subgraphs = {
                                1
                                1
                                };

2020-11-20 09:13 UTC, annacanal commented on braph2/graph/measures/test_Diameter.m
> +
known_diameter_default = {
                          Inf
                          Inf
                         };

2020-11-20 09:13 UTC, annacanal commented on braph2/graph/measures/test_Diameter.m
> +
known_diameter_subgraphs = {
                            5
                            5
                           };

2020-11-20 09:13 UTC, annacanal commented on braph2/graph/measures/test_Diameter.m
> +                         };
known_diameter_default = {
                          Inf
                          Inf
                         };

2020-11-20 11:42 UTC, maverickyuwei commented on braph2/graph/measures/Diameter.m
> +    %
7c6b5ba

2020-11-20 11:48 UTC, maverickyuwei commented on braph2/graph/measures/Diameter.m
> +                eccentricity = g.getMeasure('Eccentricity').getValue();
259455e

2020-11-20 11:59 UTC, maverickyuwei commented on braph2/graph/measures/test_Diameter.m
> +known_diameter_subgraphs = {[1]};
6dfdc21

2020-11-20 11:59 UTC, maverickyuwei commented on braph2/graph/measures/test_Diameter.m
> +known_diameter_default = {[Inf]'};
6dfdc21

2020-11-20 11:59 UTC, maverickyuwei commented on braph2/graph/measures/test_Diameter.m
> +known_diameter_subgraphs = {[5]};
6dfdc21

2020-11-20 11:59 UTC, maverickyuwei commented on braph2/graph/measures/test_Diameter.m
> +known_diameter_default = {[Inf]};
6dfdc21

2020-11-20 11:59 UTC, maverickyuwei commented on braph2/graph/measures/test_Diameter.m
> +
6dfdc21

2020-11-20 11:59 UTC, maverickyuwei commented on braph2/graph/measures/test_Diameter.m
> +
6dfdc21

2020-11-20 11:59 UTC, maverickyuwei commented on braph2/graph/measures/test_Diameter.m
> +
6dfdc21

2020-11-20 11:59 UTC, maverickyuwei commented on braph2/graph/measures/test_Diameter.m
> +                         };
6dfdc21

2020-11-20 17:11 UTC, annacanal approved these changes

2020-11-30 07:01 UTC, giovannivolpe approved these changes

2020-11-30 07:02 UTC, merged