724 ac community structure
softmatterlab/Braph-2.0-Matlab pull request #728
Opened 2020-11-03 10:20 UTC by annacanal

- [ ] CommunityStructure
- [ ] Modularity

2020-11-03 14:16 UTC, maverickyuwei commented on braph2/graph/measures/Modularity.m
> +            % GETAVAILABLESETTINGS returns the setting available to Modularity
should it be lowercase 'm'odularity?

2020-11-03 14:22 UTC, annacanal commented on braph2/graph/measures/Modularity.m
> +            % GETAVAILABLESETTINGS returns the setting available to Modularity
According to Degree measure, we wrote here the name of the measure class, so in this case: Modularity

2020-11-03 14:25 UTC, maverickyuwei commented on braph2/graph/measures/Modularity.m
> +            % GETAVAILABLESETTINGS returns the setting available to Modularity
I see, the same pattern as community structure as well!

2020-11-09 15:27 UTC, giovannivolpe requested changes
errors in unittest... see skype

2020-11-09 17:09 UTC, merged