715-yc-Radius
softmatterlab/Braph-2.0-Matlab pull request #738
Opened 2020-11-19 18:43 UTC by maverickyuwei

2020-11-20 09:21 UTC, annacanal requested changes

2020-11-20 09:21 UTC, annacanal commented on braph2/graph/measures/Radius.m
> +    %
no points at the end

2020-11-20 09:21 UTC, annacanal commented on braph2/graph/measures/Radius.m
> +                eccentricity = g.getMeasure('Eccentricity').getValue();
eccentricity = g.getMeasureValue('Eccentricity');

2020-11-20 09:21 UTC, annacanal commented on braph2/graph/measures/test_Radius.m
> +
Similarly to test_Diameter, dont need '[ ]'
known_radius_subgraphs = {0};

2020-11-20 13:51 UTC, maverickyuwei commented on braph2/graph/measures/Radius.m
> +    %
e6ae4b0

2020-11-20 13:52 UTC, maverickyuwei commented on braph2/graph/measures/Radius.m
> +                eccentricity = g.getMeasure('Eccentricity').getValue();
453a4c6

2020-11-20 13:54 UTC, maverickyuwei commented on braph2/graph/measures/test_Radius.m
> +
3f7a022

2020-11-20 16:01 UTC, annacanal approved these changes

2020-11-30 07:02 UTC, giovannivolpe approved these changes

2020-11-30 07:02 UTC, merged