714-yc-PathTransitivity
softmatterlab/Braph-2.0-Matlab pull request #739
Opened 2020-11-19 18:55 UTC by maverickyuwei

closes #714

2020-12-02 15:39 UTC, maverickyuwei commented
Up to date by merging develop 8cf01df

2020-12-02 16:46 UTC, annacanal requested changes

2020-12-02 16:46 UTC, annacanal commented on braph2/graph/measures/test_PathTransitivity.m
> +
add more space after a fractional number
```

known_path_transitivity = {[
    0     2/3    2/3   0
    2/3   0      1     4/9
    2/3   1      0     4/9
    0     4/9    4/9   0
    ]};
```

2020-12-02 16:46 UTC, annacanal commented on braph2/graph/measures/test_PathTransitivity.m
> +    0   4/9 4/9 0]};
align numbers in matrices
make it more clear

2020-12-02 16:46 UTC, annacanal commented on braph2/graph/measures/PathTransitivity.m
> +    % PathTransitivity methods:
It is calculated

2020-12-02 16:46 UTC, annacanal commented on braph2/graph/measures/PathTransitivity.m
> +            %
remove from comment GraphWU and MultiplexGraphBU(its there twice)

2020-12-02 16:46 UTC, annacanal commented on braph2/graph/measures/PathTransitivity.m
> +            % graph
all in one line:
% CALCULATE calculates the path transitivity pairwise matrix of a graph

2020-12-02 16:46 UTC, annacanal commented on braph2/graph/measures/PathTransitivity.m
> +                'shortest-paths between all pairs of nodes.' ...
within a layer

2020-12-02 16:46 UTC, annacanal commented on braph2/graph/measures/PathTransitivity.m
> +        end
Wasn't it just for Binary Undirected graphs?
Remove GraphWU and  MultiplexGraphWU

2020-12-02 17:47 UTC, maverickyuwei commented on braph2/graph/measures/test_PathTransitivity.m
> +
495b6f0

2020-12-02 17:47 UTC, maverickyuwei commented on braph2/graph/measures/test_PathTransitivity.m
> +    0   4/9 4/9 0]};
495b6f0

2020-12-02 17:55 UTC, maverickyuwei commented on braph2/graph/measures/PathTransitivity.m
> +    % PathTransitivity methods:
0b756f5

2020-12-02 17:56 UTC, maverickyuwei commented on braph2/graph/measures/PathTransitivity.m
> +            %
489b385

2020-12-02 17:57 UTC, maverickyuwei commented on braph2/graph/measures/PathTransitivity.m
> +            % graph
827cf21

2020-12-02 17:58 UTC, maverickyuwei commented on braph2/graph/measures/PathTransitivity.m
> +                'shortest-paths between all pairs of nodes.' ...
909b330

2020-12-02 18:04 UTC, maverickyuwei commented on braph2/graph/measures/PathTransitivity.m
> +        end
Yes, it was just for the Binary Undirected graph.
But the thing is, it would not pass "test MeasurementCON_BUD" the unit test if I put only GraphBU.
The reason is that MeasurementCON_BUD check the measure compatible with the Weighted Undirected graph.
Therefore, it causes the error as this particular measure is only compatible with the Binary Undirected graph.

As Emiliano recommended, just put GraphWU there because GraphWU contains GraphBU.

It would be valuable to learn from your opinion :)

2020-12-03 08:42 UTC, annacanal requested changes

2020-12-03 08:42 UTC, annacanal commented on braph2/graph/measures/PathTransitivity.m
> +        end
Oh I see the problem!
In that case maybe we could do as the previous code, and before calculating adding:

```
if g.is_binary():
       calculate
```

2020-12-03 08:42 UTC, annacanal commented on braph2/graph/measures/PathTransitivity.m
> +            path_transitivity = cell(L, 1);
```

So here add the if, to just calculate when is binary graph

L = g.layernumber();
**if g.is_binary()**
            path_transitivity = cell(L, 1);

```

2020-12-03 13:38 UTC, maverickyuwei commented on braph2/graph/measures/PathTransitivity.m
> +            path_transitivity = cell(L, 1);
a2466e6
Yes, I implemented it accordingly.
Only calculate in the binary case.
Return 0 in the weighted case.

2020-12-03 13:43 UTC, annacanal approved these changes

2021-01-11 14:37 UTC, merged