713-yc-EdgeNumberDistance
softmatterlab/Braph-2.0-Matlab pull request #742
Opened 2020-11-27 16:04 UTC by maverickyuwei

closes issue #713

2020-12-02 14:59 UTC, annacanal requested changes
You need to update this branch with develop.
braph2 command gives an error in this branch:

Error using cd
Cannot CD to /home/annacg/Documents/Braph-2.0-Matlab/braph2/graph/measures/MEX_SRC (Name is nonexistent or not a directory).

Error in compile_mex (line 22)
    cd(path_files)

Error in braph2 (line 42)
    compile_mex

2020-12-02 15:25 UTC, maverickyuwei commented
> You need to update this branch with develop.
> braph2 command gives an error in this branch that will be updated with develop:
> 
> Error using cd
> Cannot CD to /home/annacg/Documents/Braph-2.0-Matlab/braph2/graph/measures/MEX_SRC (Name is nonexistent or not a directory).
> 
> Error in compile_mex (line 22)
> cd(path_files)
> 
> Error in braph2 (line 42)
> compile_mex

Done, b38eecb
Thank you Anna, this up-to-date check will be always verified from now on.

2020-12-02 16:30 UTC, annacanal requested changes

2020-12-02 16:30 UTC, annacanal commented on braph2/graph/measures/EdgeNumberDistance.m
> +    % between two nodes.
Add one empty comment line before it is calculated
%
% It is calculated as the number of edges in the shortest weighted path
% between two nodes.

2020-12-02 16:30 UTC, annacanal commented on braph2/graph/measures/EdgeNumberDistance.m
> +    % between two nodes.
also: within the same layer

2020-12-02 16:30 UTC, annacanal commented on braph2/graph/measures/EdgeNumberDistance.m
> +            % See also Measure, Distance, GraphWU, GraphWD, MultiplexGraphWU, MultiplexGraphWD.
No GraphBD, GraphBU... not binary

2020-12-02 16:30 UTC, annacanal commented on braph2/graph/measures/EdgeNumberDistance.m
> +                'the number of edges in the shortest weighted path between two nodes. ' ...
between two nodes within a layer

2020-12-02 16:30 UTC, annacanal commented on braph2/graph/measures/test_EdgeNumberDistance.m
> +edge_number_distance = EdgeNumberDistance(g);;
delete one: ';'

2020-12-02 16:30 UTC, annacanal commented on braph2/graph/measures/test_EdgeNumberDistance.m
> +edge_number_distance = EdgeNumberDistance(g);;
same here

2020-12-02 16:30 UTC, annacanal commented on braph2/graph/measures/test_EdgeNumberDistance.m
> +edge_number_distance = EdgeNumberDistance(g);;
same here

2020-12-02 16:30 UTC, annacanal commented on braph2/graph/measures/test_EdgeNumberDistance.m
> +edge_number_distance = EdgeNumberDistance(g);;
same here

2020-12-02 18:10 UTC, maverickyuwei commented on braph2/graph/measures/EdgeNumberDistance.m
> +    % between two nodes.
45664dd

2020-12-02 18:12 UTC, maverickyuwei commented on braph2/graph/measures/EdgeNumberDistance.m
> +            % See also Measure, Distance, GraphWU, GraphWD, MultiplexGraphWU, MultiplexGraphWD.
32cd066

2020-12-02 18:13 UTC, maverickyuwei commented on braph2/graph/measures/EdgeNumberDistance.m
> +                'the number of edges in the shortest weighted path between two nodes. ' ...
8034e79

2020-12-02 18:14 UTC, maverickyuwei commented on braph2/graph/measures/test_EdgeNumberDistance.m
> +edge_number_distance = EdgeNumberDistance(g);;
778dbcc

2020-12-02 18:22 UTC, maverickyuwei commented on braph2/graph/measures/test_EdgeNumberDistance.m
> +edge_number_distance = EdgeNumberDistance(g);;
778dbcc

2020-12-02 18:22 UTC, maverickyuwei commented on braph2/graph/measures/test_EdgeNumberDistance.m
> +edge_number_distance = EdgeNumberDistance(g);;
778dbcc

2020-12-02 18:22 UTC, maverickyuwei commented on braph2/graph/measures/test_EdgeNumberDistance.m
> +edge_number_distance = EdgeNumberDistance(g);;
778dbcc

2020-12-03 08:49 UTC, annacanal approved these changes

2021-01-11 14:36 UTC, giovannivolpe approved these changes

2021-01-11 14:37 UTC, merged