Assert with error comments
softmatterlab/Braph-2.0-Matlab pull request #767
Opened 2021-01-18 17:32 UTC by egolol

Comments for assert_wth_error class

2021-01-18 17:33 UTC, annacanal approved these changes

2021-01-18 17:35 UTC, c-yuwei approved these changes

2021-01-19 08:28 UTC, giovannivolpe requested changes

2021-01-19 08:28 UTC, giovannivolpe commented on braph2genesis/test/assert_with_error.m
> +%  given by the VARARGIN.
VARARGIN is not a format, but a series of variables.
in code they should be referred to as varargin{1}, varargin{2}, ... 
Please, explain it.

2021-01-19 08:29 UTC, giovannivolpe commented on braph2genesis/test/assert_with_error.m
> +%  given by the VARARGIN.
Also, add a base case without varargin as first case

2021-01-19 13:32 UTC, annacanal approved these changes

2021-01-19 13:45 UTC, c-yuwei approved these changes

2021-01-19 13:48 UTC, c-yuwei approved these changes

2021-01-19 13:48 UTC, c-yuwei commented on braph2genesis/test/assert_with_error.m
> +%  error with ERRORIDENTIFIER is thrown by the CODE which uses the variables
Maybe 'error' with capital E?

2021-01-19 14:03 UTC, c-yuwei commented on braph2genesis/test/assert_with_error.m
> +%  error with ERRORIDENTIFIER is thrown by the CODE which uses the variables
no, it is not the beginning of the sentence.

2021-01-19 18:42 UTC, giovannivolpe reviewed
Seems done, let's double-check and merge it together when we speak

2021-01-20 16:45 UTC, giovannivolpe approved these changes

2021-01-20 16:45 UTC, merged