Update test_Format.m
softmatterlab/Braph-2.0-Matlab pull request #769
Opened 2021-01-18 18:07 UTC by egolol

2021-01-18 18:07 UTC, annacanal approved these changes

2021-01-18 18:07 UTC, c-yuwei approved these changes

2021-01-18 18:08 UTC, c-yuwei approved these changes

2021-01-19 08:32 UTC, giovannivolpe requested changes

2021-01-19 08:32 UTC, giovannivolpe commented on braph2genesis/src/ds/test_Format.m
> +clear element_class_list
why do you need to clear this?

2021-01-19 08:32 UTC, giovannivolpe commented on braph2genesis/src/ds/test_Format.m
> +
You should also add the good cases, given by elements obtained from itemlist.

2021-01-19 10:22 UTC, egolol commented on braph2genesis/src/ds/test_Format.m
> +
I don't understand this, if you want items defined in Element, do I uncomment Element functions to do this? For example getElementList. Or, as I am doing, defining an array of pointers of items of Element subclasses.

2021-01-19 11:29 UTC, giovannivolpe requested changes

2021-01-19 11:29 UTC, giovannivolpe commented on braph2genesis/src/ds/test_Format.m
> +Format.checkFormat(Format.ITEMLIST, element_item_list)
This should be a for cycle over all possible correct values

2021-01-19 11:29 UTC, giovannivolpe commented on braph2genesis/src/ds/test_Format.m
> +element_item_list = cellfun(@(x) eval([x '()']), element_item_list_names, 'UniformOutput', false);
make "element_item_list" as value
addd more cases, such as a list of {'Element'}, ... taken with a for cycle from element_list

2021-01-19 18:43 UTC, giovannivolpe reviewed
Let's double-check and revise it together when we speak

2021-01-20 16:58 UTC, giovannivolpe approved these changes

2021-01-20 16:58 UTC, merged