773 all atlas
softmatterlab/Braph-2.0-Matlab pull request #774
Opened 2021-01-28 18:04 UTC by egolol

2021-01-28 18:19 UTC, giovannivolpe requested changes

2021-01-28 18:19 UTC, giovannivolpe commented on braph2genesis/src/atlas/_BrainAtlas.gen.m
> +
add seealso

2021-01-28 18:19 UTC, giovannivolpe commented on braph2genesis/src/atlas/_BrainAtlas.gen.m
> +IndexedDictionary('IT_CLASS', 'BrainRegion', 'IT_KEY', 1)
I think this is not necessary in this case, because it's the default

2021-01-28 18:19 UTC, giovannivolpe commented on braph2genesis/src/atlas/_BrainRegion.gen.m
> +end
these should not be here. Use the standard methods of element instead

2021-01-28 20:45 UTC, annacanal commented on braph2genesis/src/atlas/_BrainRegion.gen.m
> +end
Then we create a prop called Position containing these 3 other props(x,y,z) ?

2021-01-29 06:37 UTC, giovannivolpe approved these changes

2021-01-29 06:38 UTC, giovannivolpe commented
When you implement the Import and Export elements, make them derive directly from Element for now

2021-01-29 09:42 UTC, giovannivolpe commented
Please, add _Importer.gen.m and _Exporter.gen.m (see attachments) o src/util as base elements for all importers and exporters. You'll also need to modify them
[Archive.zip](https://github.com/softmatterlab/Braph-2.0-Matlab/files/5892970/Archive.zip)

2021-01-29 15:02 UTC, giovannivolpe requested changes
small comments, after you have addressed them you can move to the next section

2021-01-29 15:02 UTC, giovannivolpe commented on braph2genesis/src/atlas/_ExporterBrainAtlasTXT.gen.m
> +BrainAtlas()
not needed

2021-01-29 15:02 UTC, giovannivolpe commented on braph2genesis/src/atlas/_ExporterBrainAtlasXLS.gen.m
> +BrainAtlas()
not needed

2021-01-29 16:16 UTC, c-yuwei commented on braph2genesis/src/atlas/_ImporterBrainAtlasXLS.gen.m
> +ImporterBrainAtlasXLS imports a brain atlas from an XLS/XLSX file.
08c783f0

2021-01-29 19:04 UTC, egolol commented
I deleted ImporterBrainAtlasTXT/XLS comments, because they create an error. please redo.

2021-01-29 20:02 UTC, c-yuwei commented
Resolved the TXT/XLS comments error (162a63f1)
it was due to the apostrophe character.
![image](https://user-images.githubusercontent.com/30530538/106321817-22d4d000-6275-11eb-80d1-7f35221518c8.png)

2021-02-01 06:24 UTC, giovannivolpe requested changes

2021-02-01 06:24 UTC, giovannivolpe commented on braph2genesis/src/atlas/_BrainAtlas.gen.m
> +
specify the element in settings

2021-02-01 06:24 UTC, giovannivolpe commented on braph2genesis/src/atlas/_BrainSurface.gen.m
> +TRIANGLES (data, cvector) is the coordinate of the brain surface.
check the definitions of the various properties

2021-02-01 08:52 UTC, giovannivolpe approved these changes

2021-02-02 09:57 UTC, giovannivolpe reviewed
Changes the names "BrainMesh_..." to "human_..."

2021-02-02 09:57 UTC, giovannivolpe commented on braph2genesis/braph2/braph2.m
> +addpath([src_dir filesep 'atlas' filesep 'brainsurfs'])
move brainsurfs to top level directory (same level as src)

2021-02-02 09:57 UTC, giovannivolpe commented on braph2genesis/genesis/genesis.m
> +mkdir([target_dir fp 'src' fp 'atlas' fp 'brainsurfs'])
mkdir([target_dir fp 'brainsurfs'])

2021-02-02 09:57 UTC, giovannivolpe commented on braph2genesis/genesis/genesis.m
> +mkdir([target_dir fp 'src' fp 'atlas' fp 'brainsurfs'])
make all consequent necessary changes

2021-02-02 09:57 UTC, giovannivolpe commented on braph2genesis/src/atlas/_BrainSurface.gen.m
> +
eliminate extra line

2021-02-02 09:57 UTC, giovannivolpe commented on braph2genesis/src/atlas/_BrainSurface.gen.m
> +
add correctness check in coordinates and triangles (basically using their numbers)

2021-02-02 10:04 UTC, giovannivolpe reviewed
Important comment, PlotBrainSurf should have as input a BrainSurface element

and PlotBrainAtlas a BrainAtlas

2021-02-02 10:04 UTC, giovannivolpe commented on braph2genesis/src/atlas/PlotBrainSurf.m
> +        brain_surf_file  % file of the brain surface
BrainSurface element, not file
In brainSurface, you should have the code to import (maybe also export the nv files)

2021-02-02 10:04 UTC, giovannivolpe commented on braph2genesis/src/atlas/PlotBrainSurf.m
> +        function bs = PlotBrainSurf(brain_surf_file, varargin)
should have element BrainSurface as input

2021-02-02 10:31 UTC, egolol commented on braph2genesis/src/atlas/_BrainSurface.gen.m
> +
like assert that its a number? or that 1 dimension of the input is equal to that number?

2021-02-02 16:14 UTC, merged