777 cohort workflow subjects
softmatterlab/Braph-2.0-Matlab pull request #780
Opened 2021-02-02 17:55 UTC by annacanal

- [x] folder src/cohort + changes to braph2, genesis, test, etc...
- [ ] _Group.gen.m, _Subject.gen.m (see attached files, modify as needed)
[cohort.zip](https://github.com/giovannivolpe/Braph-2.0-Genesis/files/5910842/cohort.zip)
- [ ] folder worflows/connectivity, functional, structural + changes as needed

- [ ] _SubjectCON.gen.m + import + export + example files
- [ ] CON import/export TXT

- [ ] _SubjectFUN.gen.m + import + export + example files
- [ ] FUN import/export TXT

- [ ] _SubjectST.gen.m + import + export + example files
- [ ] ST import/export TXT

2021-02-04 10:26 UTC, giovannivolpe reviewed
add gitignore for .DS_store files

2021-02-04 10:26 UTC, giovannivolpe commented on braph2genesis/braph2/braph2.m
> +workflows_dir_list = dir(workflows_dir);   % get the folder contents
leave only one space before % (new approach)

2021-02-04 10:26 UTC, giovannivolpe commented on braph2genesis/src/cohort/_Group.gen.m
> +IndexedDictionary('IT_CLASS', 'Subject', 'IT_KEY', 1)
This should not be needed as it's the default value

2021-02-04 10:26 UTC, giovannivolpe commented on braph2genesis/src/cohort/_Group.gen.m
> +end
remove because they can be called from SUB_DICT

2021-02-04 10:26 UTC, giovannivolpe commented on braph2genesis/src/cohort/_Subject.gen.m
> +end
Not needed.
One can use directly subclasses('Subject')

2021-02-04 10:26 UTC, giovannivolpe commented on braph2genesis/test/test_braph2.m
> +workflows_dir_list = workflows_dir_list(~ismember({workflows_dir_list(:).name}, {'.', '..'}));  % remove '.' and '..'
single space before %

2021-02-04 10:32 UTC, giovannivolpe requested changes
Please, make sure you also add .DS_Store files to the gitignore file

2021-02-04 10:48 UTC, annacanal commented on braph2genesis/src/cohort/_Group.gen.m
> +end
ok

2021-02-04 21:31 UTC, c-yuwei approved these changes

2021-02-05 08:51 UTC, giovannivolpe reviewed
Let's check it together and then merge it

2021-02-06 09:53 UTC, giovannivolpe approved these changes

2021-02-06 09:53 UTC, merged