779 brain surface value checks
softmatterlab/Braph-2.0-Matlab pull request #781
Opened 2021-02-03 14:40 UTC by annacanal

Add checks values (¡check_value!) to the props

- [x] VERTEX_NUMBER
- [x] COORDINATES
- [ ] TRIANGLES_NUMBER
- [ ] TRIANGLES

2021-02-03 15:12 UTC, annacanal commented
Not sure if I forgot some check. I added all the checks I could remember we talked

2021-02-03 21:25 UTC, c-yuwei approved these changes

2021-02-03 21:25 UTC, c-yuwei commented on braph2genesis/src/atlas/_BrainSurface.gen.m
> +check = isequal(bs.get('TRIANGLES_NUMBER'), size(value, 1)) && size(value, 1)*size(value, 2) >= bs.get('VERTEX_NUMBER')
I was thinking what if we divide the check into two as it is two different conditions.

2021-02-04 09:54 UTC, annacanal commented on braph2genesis/src/atlas/_BrainSurface.gen.m
> +check = isequal(bs.get('TRIANGLES_NUMBER'), size(value, 1)) && size(value, 1)*size(value, 2) >= bs.get('VERTEX_NUMBER')
This can be detected in the message when it fails. I don't think we can have 2 checks for prop

2021-02-04 10:09 UTC, giovannivolpe requested changes
I've made some comments.

Also, add in each of the 4 properties a ¡check_prop! to check that they are positive integers

2021-02-04 10:09 UTC, giovannivolpe commented on braph2genesis/src/atlas/_BrainSurface.gen.m
> +check = isequal(bs.get('TRIANGLES_NUMBER'), size(value, 1)) && size(value, 1)*size(value, 2) >= bs.get('VERTEX_NUMBER')
I don't understand "&& size(value, 1)*size(value, 2) >= bs.get('VERTEX_NUMBER'")

I think the check should be different, i.e., something like all(all(value <= bs.get('VERTEX_NUMBER'"))

2021-02-04 10:21 UTC, annacanal commented on braph2genesis/src/atlas/_BrainSurface.gen.m
> +check = isequal(bs.get('TRIANGLES_NUMBER'), size(value, 1)) && size(value, 1)*size(value, 2) >= bs.get('VERTEX_NUMBER')
Ah I understand!
 I was just checking the number of vertexes used to create triangles was the same or bigger than vertex_number, since vertexes can be repeated. but of course, still need to check if it is the specific vertex as you say.

2021-02-04 10:40 UTC, annacanal commented on braph2genesis/src/atlas/_BrainSurface.gen.m
> +check = isequal(bs.get('TRIANGLES_NUMBER'), size(value, 1)) && size(value, 1)*size(value, 2) >= bs.get('VERTEX_NUMBER')
Ok, no, Im confused with your proposed checking.
I think what I wanted to do is:

#triangles * 3 (vertices/triangle) >= #vertices
size(value, 1)*3 >= bs.get('VERTEX_NUMBER'")

2021-02-04 12:47 UTC, c-yuwei approved these changes

2021-02-05 08:48 UTC, giovannivolpe requested changes
Please, have a look at my comments

2021-02-05 08:48 UTC, giovannivolpe commented on braph2genesis/src/atlas/_BrainSurface.gen.m
> +check = value > 0 && isnumeric(value)
&& isnumeric(value) is not needed because it's already checked as scalar

2021-02-05 08:48 UTC, giovannivolpe commented on braph2genesis/src/atlas/_BrainSurface.gen.m
> +check = value > 0 && isnumeric(value)
maybe you can check that it's integer with isinteger

2021-02-05 08:48 UTC, giovannivolpe commented on braph2genesis/src/atlas/_BrainSurface.gen.m
> +1
Remove,
I'd leave the default at 0

2021-02-05 08:48 UTC, giovannivolpe commented on braph2genesis/src/atlas/_BrainSurface.gen.m
> +check = value > 0 && isnumeric(value)
check >= 0

2021-02-05 08:48 UTC, giovannivolpe commented on braph2genesis/src/atlas/_BrainSurface.gen.m
> +check = all(all(value >= 0)) && isnumeric(value)
Check not needed, coordiantes can also be negative

2021-02-05 08:48 UTC, giovannivolpe commented on braph2genesis/src/atlas/_BrainSurface.gen.m
> +zeros(1, 3)
I'd leave the default

2021-02-05 08:48 UTC, giovannivolpe commented on braph2genesis/src/atlas/_BrainSurface.gen.m
> +1
same as above

2021-02-05 08:48 UTC, giovannivolpe commented on braph2genesis/src/atlas/_BrainSurface.gen.m
> +check = all(all(value > 0)) && isnumeric(value)
not needed (implicit in check_value)

2021-02-05 08:48 UTC, giovannivolpe commented on braph2genesis/src/atlas/_BrainSurface.gen.m
> +ones(1, 3)
also here, I'd leave the default

2021-02-05 09:16 UTC, egolol commented on braph2genesis/src/atlas/_BrainSurface.gen.m
> +check = isequal(bs.get('TRIANGLES_NUMBER'), size(value, 1)) && size(value, 1)*size(value, 2) >= bs.get('VERTEX_NUMBER')
Imagine a cube, you need 4 vertex number to describe it. For its surface, you need 2 triangles per side * 6 sides. So vertex number is not bigger than the triangle number.

2021-02-05 09:25 UTC, egolol commented on braph2genesis/src/atlas/_BrainSurface.gen.m
> +check = value > 0 && isnumeric(value)
I think you meant value.

2021-02-07 04:56 UTC, giovannivolpe approved these changes

2021-02-07 05:00 UTC, merged