Strength and StrengthAV
softmatterlab/Braph-2.0-Matlab pull request #793
Opened 2021-02-11 11:10 UTC by egolol

2021-02-11 12:58 UTC, annacanal requested changes

2021-02-11 12:58 UTC, annacanal commented on braph2genesis/measures/_Strength.gen.m
> +    end
we don't need this if now.

just:
 Aii = A{li, li};

2021-02-11 12:58 UTC, annacanal commented on braph2genesis/measures/_StrengthAV.gen.m
> +strength_av = calculateValue@Strength(m, prop);
call this strength

2021-02-11 12:58 UTC, annacanal commented on braph2genesis/measures/_StrengthAV.gen.m
> +    strength_av(li) = {mean(strength_av{li})};
strength_av(li) = {mean(strength{li})};

2021-02-11 14:30 UTC, annacanal commented on braph2genesis/measures/_Strength.gen.m
>      A = cell2mat(A);
this line shouldn't be there. (A = cell2mat(A);)
we want to treat them now always with cell, like in multiplex.
Aii = A{li, li}; in this way, it goes to the diagonal of supra-adjacency matrix : A{1, 1}, A{2,2}, ..A{L, L}

Check _Degree, should be the same inside the loop, without binarizing

2021-02-11 14:32 UTC, c-yuwei approved these changes

2021-02-11 14:36 UTC, annacanal approved these changes

2021-02-11 16:56 UTC, c-yuwei requested changes

2021-02-11 16:56 UTC, c-yuwei commented on braph2genesis/measures/_StrengthAv.gen.m
> +s_outside_g = Strength('G', g);
should be s_outside_g = StrengthAv('G', g);

2021-02-11 16:56 UTC, c-yuwei commented on braph2genesis/measures/_StrengthAv.gen.m
> +strength_av = Strength('G', g);
Should be strength_av = StrengthAv('G', g);

2021-02-11 17:52 UTC, annacanal commented on braph2genesis/measures/_StrengthAv.gen.m
> +strength_av = Strength('G', g);
Hi now I see this error on line 81.
When multiplex: g = MultiplexGraphWU('B', B);
if not the test won't pass

2021-02-11 17:53 UTC, annacanal requested changes

2021-02-11 17:53 UTC, annacanal commented on braph2genesis/measures/_Strength.gen.m
> +g = MultiplexGraphWU('B', {B});
g = MultiplexGraphWU('B', B);
Here B is already a cell

2021-02-11 17:53 UTC, annacanal commented on braph2genesis/measures/_StrengthAv.gen.m
> +g = GraphWU('B', {B});
g = MultiplexGraphWU('B', B);

2021-02-11 18:09 UTC, egolol commented on braph2genesis/measures/_StrengthAv.gen.m
> +strength_av = Strength('G', g);
ugg forgot to change this.... sometimes i change stuff in the tmp, and forget to change it at the genesis

2021-02-12 07:46 UTC, annacanal approved these changes

2021-02-12 10:03 UTC, c-yuwei approved these changes

2021-02-12 10:27 UTC, giovannivolpe approved these changes

2021-02-12 10:27 UTC, merged