InDegree and InDegreeAV
softmatterlab/Braph-2.0-Matlab pull request #796
Opened 2021-02-11 15:33 UTC by c-yuwei

2021-02-11 17:48 UTC, annacanal requested changes

2021-02-11 17:48 UTC, annacanal commented on braph2genesis/measures/_InDegree.gen.m
> +InDegree < Measure (m, degree) is the graph degree.
in-degree

2021-02-11 17:48 UTC, annacanal commented on braph2genesis/measures/_InDegree.gen.m
> +g = MultiplexGraphBD('B', {B});
g = MultiplexGraphBD('B', B);
B is already a cell here

2021-02-11 17:48 UTC, annacanal commented on braph2genesis/measures/_InDegree.gen.m
> +g = MultiplexGraphWD('B', {B});
g = MultiplexGraphBD('B', B);
B is already a cell here

2021-02-11 17:48 UTC, annacanal commented on braph2genesis/measures/_InDegreeAv.gen.m
> +InDegreeAv < InDegree (m, degree) is the graph degree.
is the graph average in-degree.

2021-02-11 17:48 UTC, annacanal commented on braph2genesis/measures/_InDegreeAv.gen.m
> +M (result, cell) is the in-degree-av.
is the average in-degree

2021-02-11 17:48 UTC, annacanal commented on braph2genesis/measures/_InDegreeAv.gen.m
> +g = MultiplexGraphBD('B', {B});
same than before, B not {B}

2021-02-11 17:48 UTC, annacanal commented on braph2genesis/measures/_InDegreeAv.gen.m
> +g = MultiplexGraphWD('B', {B});
same than before, B not {B}

2021-02-11 20:35 UTC, c-yuwei commented on braph2genesis/measures/_InDegreeAv.gen.m
> +InDegreeAv < InDegree (m, degree) is the graph degree.
d5b4c69f

2021-02-11 20:35 UTC, c-yuwei commented on braph2genesis/measures/_InDegree.gen.m
> +InDegree < Measure (m, degree) is the graph degree.
d5b4c69f

2021-02-11 20:37 UTC, c-yuwei commented on braph2genesis/measures/_InDegree.gen.m
> +g = MultiplexGraphBD('B', {B});
facdda24

2021-02-11 20:37 UTC, c-yuwei commented on braph2genesis/measures/_InDegree.gen.m
> +g = MultiplexGraphWD('B', {B});
facdda24

2021-02-11 20:37 UTC, c-yuwei commented on braph2genesis/measures/_InDegreeAv.gen.m
> +InDegreeAv < InDegree (m, degree) is the graph degree.
facdda24

2021-02-11 20:39 UTC, c-yuwei commented on braph2genesis/measures/_InDegreeAv.gen.m
> +M (result, cell) is the in-degree-av.
be2c4e02

2021-02-11 20:39 UTC, c-yuwei commented on braph2genesis/measures/_InDegreeAv.gen.m
> +g = MultiplexGraphBD('B', {B});
facdda2

2021-02-11 20:39 UTC, c-yuwei commented on braph2genesis/measures/_InDegreeAv.gen.m
> +g = MultiplexGraphWD('B', {B});
facdda2

2021-02-12 07:01 UTC, egolol approved these changes

2021-02-12 07:42 UTC, annacanal approved these changes

2021-02-12 10:26 UTC, giovannivolpe approved these changes

2021-02-12 11:06 UTC, merged