Eccentricity, EccentricityAv, Radius and Diameter
softmatterlab/Braph-2.0-Matlab pull request #798
Opened 2021-02-11 22:48 UTC by c-yuwei

2021-02-16 20:03 UTC, annacanal requested changes
just typo things^^

2021-02-16 20:03 UTC, annacanal commented on braph2genesis/measures/_EccentricityAv.gen.m
> +eccentritivity = calculateValue@Eccentricity(m, prop);
typo: **eccentricity** instead of eccentritivity

2021-02-16 20:03 UTC, annacanal commented on braph2genesis/measures/_EccentricityAv.gen.m
> +    eccentritivity_av(li) = {mean(eccentritivity{li})};
same for: **eccentricity_av** instead of eccentritivity_av

2021-02-17 20:35 UTC, c-yuwei commented on braph2genesis/measures/_Eccentricity.gen.m
> +bct_eccentricity = cell(g.layernumber(), 1);
63dc378e

2021-02-17 20:36 UTC, c-yuwei commented on braph2genesis/measures/_Eccentricity.gen.m
> +bct_eccentricity = cell(g.layernumber(), 1);
thank you anna, messed it up when i did replacement :P

2021-02-17 20:38 UTC, c-yuwei commented on braph2genesis/measures/_EccentricityAv.gen.m
> +eccentritivity = calculateValue@Eccentricity(m, prop);
9bffdde9

2021-02-17 20:38 UTC, c-yuwei commented on braph2genesis/measures/_EccentricityAv.gen.m
> +    eccentritivity_av(li) = {mean(eccentritivity{li})};
9bffdde9

2021-02-17 21:40 UTC, annacanal approved these changes

2021-02-18 13:55 UTC, c-yuwei commented
![image](https://user-images.githubusercontent.com/30530538/108367036-4e563500-71f9-11eb-8d6b-89a644efe75b.png)
The option is being integrated

2021-02-18 14:06 UTC, egolol approved these changes

2021-02-19 09:04 UTC, giovannivolpe requested changes

2021-02-19 09:04 UTC, giovannivolpe commented on braph2genesis/measures/_Diameter.gen.m
> +rule (metadata, OPTION)
missing description

2021-02-19 09:04 UTC, giovannivolpe commented on braph2genesis/measures/_Diameter.gen.m
> +A = g.get('A'); % cell matrix (for graph) or 2D-cell array (for multigraph, multiplex, etc.)
it's always cell array, change comment

2021-02-19 09:04 UTC, giovannivolpe commented on braph2genesis/measures/_Eccentricity.gen.m
> +        };
remove

2021-02-19 09:04 UTC, giovannivolpe commented on braph2genesis/measures/_Eccentricity.gen.m
> +rule (metadata, OPTION)
missing description

2021-02-19 09:04 UTC, giovannivolpe commented on braph2genesis/measures/_Eccentricity.gen.m
> +A = g.get('A'); % cell matrix (for graph) or 2D-cell array (for multigraph, multiplex, etc.)
update comment

2021-02-19 09:04 UTC, giovannivolpe commented on braph2genesis/measures/_EccentricityAv.gen.m
> +A = g.get('A'); % cell matrix (for graph) or 2D-cell array (for multigraph, multiplex, etc.)
comment

2021-02-19 09:04 UTC, giovannivolpe commented on braph2genesis/measures/_Radius.gen.m
> +rule (metadata, OPTION)
description

2021-02-19 09:04 UTC, giovannivolpe commented on braph2genesis/measures/_Radius.gen.m
> +A = g.get('A'); % cell matrix (for graph) or 2D-cell array (for multigraph, multiplex, etc.)
comment

2021-02-22 16:41 UTC, c-yuwei commented on braph2genesis/measures/_Diameter.gen.m
> +A = g.get('A'); % cell matrix (for graph) or 2D-cell array (for multigraph, multiplex, etc.)
691fec04

2021-02-22 16:41 UTC, c-yuwei commented on braph2genesis/measures/_Eccentricity.gen.m
> +A = g.get('A'); % cell matrix (for graph) or 2D-cell array (for multigraph, multiplex, etc.)
691fec04

2021-02-22 16:41 UTC, c-yuwei commented on braph2genesis/measures/_EccentricityAv.gen.m
> +A = g.get('A'); % cell matrix (for graph) or 2D-cell array (for multigraph, multiplex, etc.)
691fec04

2021-02-22 16:41 UTC, c-yuwei commented on braph2genesis/measures/_Radius.gen.m
> +A = g.get('A'); % cell matrix (for graph) or 2D-cell array (for multigraph, multiplex, etc.)
691fec04

2021-02-22 16:53 UTC, c-yuwei commented on braph2genesis/measures/_Eccentricity.gen.m
> +        };
ab00ff7b

2021-02-22 16:53 UTC, c-yuwei commented on braph2genesis/measures/_Diameter.gen.m
> +rule (metadata, OPTION)
ab00ff7b

2021-02-22 16:53 UTC, c-yuwei commented on braph2genesis/measures/_Eccentricity.gen.m
> +rule (metadata, OPTION)
ab00ff7b

2021-02-22 16:53 UTC, c-yuwei commented on braph2genesis/measures/_Radius.gen.m
> +rule (metadata, OPTION)
ab00ff7b

2021-02-22 17:01 UTC, egolol approved these changes

2021-02-22 17:12 UTC, giovannivolpe approved these changes

2021-02-22 17:12 UTC, merged