Ac multiplex graphs
softmatterlab/Braph-2.0-Matlab pull request #800
Opened 2021-02-12 13:43 UTC by annacanal

Generators for:
- [ ] MultiplexGraphBD
- [ ] MultiplexGraphBU
- [ ] MultiplexGraphWD
- [ ] MultiplexGraphWU

2021-02-12 15:37 UTC, egolol approved these changes

2021-02-12 15:37 UTC, c-yuwei approved these changes

2021-02-12 16:06 UTC, giovannivolpe requested changes
See changes to B and calculate A in BD.
Please, apply to all.

Essentially, B should only be the layer matrices (not out of diagonal terms), which then simplofies all.

The default shoudl be {[]}

2021-02-12 16:06 UTC, giovannivolpe commented on braph2genesis/graphs/_MultiplexGraphBD.gen.m
> +{[] [] []; [] [] []; [] [] []};
This could be {[]; []; []} instead, also in the others

Even better, it would be possible to have three props, B1, B2, B3

2021-02-12 16:06 UTC, giovannivolpe commented on braph2genesis/graphs/_MultiplexGraphBD.gen.m
> +end
this is not necessary if you only have the different format for B

2021-02-12 16:21 UTC, annacanal commented on braph2genesis/graphs/_MultiplexGraphBD.gen.m
> +{[] [] []; [] [] []; [] [] []};
if you have 3 props you are limiting it to 3 layers. this needs N B adjacency matrices

2021-02-13 19:08 UTC, annacanal commented on braph2genesis/graphs/_MultiplexGraphBD.gen.m
> +{[] [] []; [] [] []; [] [] []};
It actually makes the tests of elements fail. I have tried with this other format
If I have as default B just empty adjacency matrices, then the off-diagonal of the cell, are eye matrices of size equal to length({[], []}) and arent empty.
The assert of multiplex will fail since the matrices of the cell have different size.

2021-02-15 11:20 UTC, giovannivolpe approved these changes

2021-02-15 11:20 UTC, merged