790 eg triangles transitivity
softmatterlab/Braph-2.0-Matlab pull request #801
Opened 2021-02-12 15:33 UTC by egolol

2021-02-15 11:38 UTC, annacanal requested changes
Also merge the current gv-genesis-2 with the new format of multiplex graphs. you will have to adapt the tests

2021-02-15 11:38 UTC, annacanal commented on braph2genesis/measures/_Transitivity.gen.m
> +directionality_type =  g.getDirectionalityType(g.layernumber());
use L variable, that you declared on line 35

2021-02-15 11:38 UTC, annacanal commented on braph2genesis/measures/_Triangles.gen.m
> +
one extra space line -> remove

2021-02-15 11:38 UTC, annacanal commented on braph2genesis/measures/_Triangles.gen.m
> +    };
shouldnt we explain using comments the meaning of these rules? as we had in braph2?

2021-02-15 11:38 UTC, annacanal commented on braph2genesis/measures/_Triangles.gen.m
> +L = g.layernumber();
not using L later.

2021-02-15 13:43 UTC, c-yuwei approved these changes

2021-02-15 14:04 UTC, annacanal requested changes

2021-02-15 14:04 UTC, annacanal commented on braph2genesis/measures/_Triangles.gen.m
> +%% Test 2: GraphBD
adapt the format of test 2

2021-02-15 14:04 UTC, annacanal commented on braph2genesis/measures/_Transitivity.gen.m
> +
Adapt to the new format of Multiplex graphs,
It fails the test now for MultiplexGraphBU

2021-02-16 14:57 UTC, annacanal approved these changes

2021-02-17 08:20 UTC, giovannivolpe requested changes
Use format option for the rules

2021-02-17 08:20 UTC, giovannivolpe commented on braph2genesis/measures/_Triangles.gen.m
> +5
use format = option instead

2021-02-19 09:08 UTC, giovannivolpe approved these changes

2021-02-19 09:08 UTC, merged