Assortativity, Betweeness centrality, Clustering and ClusterinAV
softmatterlab/Braph-2.0-Matlab pull request #802
Opened 2021-02-13 16:54 UTC by egolol

2021-02-15 11:41 UTC, annacanal reviewed
Merge the updates from gv-genesis-2 and adapt the tests. In general all looks good

2021-02-15 13:46 UTC, c-yuwei commented
Is clustering compatible with multiplex?

2021-02-15 14:05 UTC, annacanal commented
> Is clustering compatible with multiplex?

Yes it is. One person might want to know the clustering within each layer.
Like Strength is compatible with multiplex. It will give a result per each layer

2021-02-16 12:37 UTC, c-yuwei commented on braph2genesis/measures/_Transitivity.gen.m
> +A21 = eye(4);
Adapt for new multiplex format implementation.

2021-02-17 12:54 UTC, annacanal requested changes
You are missing compatible multiplex graphs on the measures.

2021-02-17 12:54 UTC, annacanal commented on braph2genesis/measures/_Clustering.gen.m
> +GraphBD
it is also compatible to Multiplex graphs.

            list = { ...
                'GraphBD' ...
                'GraphBU', ...
                'GraphWD', ...
                'GraphWU' ...
                'MultiplexGraphBD', ...
                'MultiplexGraphBU', ...
                'MultiplexGraphWD' ...
                'MultiplexGraphWU' ...
                };

2021-02-17 12:54 UTC, annacanal commented on braph2genesis/measures/_Assortativity.gen.m
> +
also compatible to 
                'MultiplexGraphBU', ...
                'MultiplexGraphWU' ...

2021-02-17 12:54 UTC, annacanal commented on braph2genesis/measures/_BetweennessCentrality.gen.m
> +
also compatible to 
                'MultiplexGraphBD', ...
                'MultiplexGraphBU', ...
                'MultiplexGraphWD', ...
                'MultiplexGraphWU' ...

2021-02-17 12:54 UTC, annacanal commented on braph2genesis/measures/_ClusteringAv.gen.m
> +GraphBD
same also compatible to all multiplex graphs

2021-02-17 19:31 UTC, annacanal approved these changes
I updated all the measures to work with multiplex graphs. Check them

2021-02-18 13:53 UTC, c-yuwei approved these changes

2021-02-19 09:07 UTC, giovannivolpe requested changes
update all:
% adjacency matrix (for graph) or 2D-cell array (for multigraph, multiplex, etc.)

2021-02-19 09:07 UTC, giovannivolpe commented on braph2genesis/measures/_BetweennessCentrality.gen.m
> +%% ¡props_update!
leave space

2021-02-22 17:16 UTC, giovannivolpe approved these changes

2021-02-22 17:20 UTC, merged