Comments to the graph and measure in create_element
softmatterlab/Braph-2.0-Matlab pull request #805
Opened 2021-02-15 14:27 UTC by egolol

2021-02-15 16:14 UTC, annacanal requested changes
small things

2021-02-15 16:14 UTC, annacanal commented on braph2genesis/genesis/create_Element.m
> +                            ['% BOOL = ' descriptive_name '.IS_ENSEMBLE() returns true if it is an ensamble graph.']
ensamble -> ensemble

2021-02-15 16:14 UTC, annacanal commented on braph2genesis/genesis/create_Element.m
> +                            '%'
**self-connectivity**
Graphs can be self-connected or non self-connected.'

2021-02-15 16:14 UTC, annacanal commented on braph2genesis/genesis/create_Element.m
> +                                '% See also is_ensemble, getGraphType, getConnectivityType, getDirectionalityType, getNegativityType.'
getNegativityType ->  **getSelfConnectivityType**

2021-02-15 16:14 UTC, annacanal commented on braph2genesis/genesis/create_Element.m
> +                            '%   Shape can be global, nodal, binodal.'
Shape can be global, nodal or binodal.

2021-02-15 16:14 UTC, annacanal commented on braph2genesis/genesis/create_Element.m
> +                            '%   Scope can be unilayer, superglobal or bilayer.'
I would write in the following order, as it appears in line 42 of this file create_Element
Scope can be superglobal, unilayer or bilayer.

2021-02-15 16:21 UTC, c-yuwei approved these changes

2021-02-16 10:32 UTC, annacanal approved these changes

2021-02-17 08:23 UTC, giovannivolpe requested changes

2021-02-17 08:23 UTC, giovannivolpe commented on braph2genesis/genesis/create_Element.m
> +                            ['% BOOL = ' descriptive_name '.IS_ENSEMBLE() returns true if it is an ensemble graph.']
make it concrete with two cases: one for true and one for false

2021-02-17 08:23 UTC, giovannivolpe commented on braph2genesis/genesis/create_Element.m
> +                            '%'
Add case with number of layers in varaging, also in methods below

2021-03-24 07:24 UTC, closed without merging