Community Structure
softmatterlab/Braph-2.0-Matlab pull request #807
Opened 2021-02-16 10:15 UTC by egolol

2021-02-16 12:31 UTC, c-yuwei approved these changes

2021-02-22 13:51 UTC, annacanal requested changes

2021-02-22 13:51 UTC, annacanal commented on braph2genesis/measures/_CommunityStructure.gen.m
> +1
Gamma is a PARAMETER, not METADATA

METADATA     Metadata NOT used in the calculation of the results (does not allow callbacks).

2021-02-22 13:51 UTC, annacanal commented on braph2genesis/measures/_CommunityStructure.gen.m
> +
it think these 2 are also Parameter

2021-02-22 13:51 UTC, annacanal commented on braph2genesis/measures/_CommunityStructure.gen.m
> +quality_function (metadata, SCALAR)
this is DATA. already calculated quality_function, which is used to calculate community structure

2021-02-22 13:51 UTC, annacanal commented on braph2genesis/measures/_CommunityStructure.gen.m
> +
actually I think that OM (the B matrix) and the initial community affiliation (M0) are DATA

2021-02-22 17:56 UTC, annacanal requested changes

2021-02-22 17:56 UTC, annacanal commented on braph2genesis/measures/_CommunityStructure.gen.m
> +gamma (data, SCALAR)
parameter

2021-02-23 18:18 UTC, annacanal approved these changes

2021-02-24 11:42 UTC, giovannivolpe requested changes
Add definitions to props

2021-02-24 11:42 UTC, giovannivolpe commented on braph2genesis/measures/_CommunityStructure.gen.m
> +%%%% ¡settings!
add def

2021-02-25 14:49 UTC, giovannivolpe approved these changes

2021-02-25 14:50 UTC, merged