Graphs measures ensemble
softmatterlab/Braph-2.0-Matlab pull request #809
Opened 2021-02-17 16:51 UTC by egolol

2021-02-17 20:25 UTC, annacanal requested changes

2021-02-17 20:25 UTC, annacanal commented on braph2genesis/graphs/_GraphBDEnsemble.gen.m
> +A (result, adjacency) is the non-negative average adjacency matrix of the ensemble of binary directed graphs.
this should be:  **cell** or **matrix** ?
Have you tested? it fails all the ensembles because of that and don't know if other things

2021-02-18 21:10 UTC, c-yuwei commented
Following ensemble graphs are implemented:
- MultigraphBUT/BUDEnsemble
- MultiplexGraphWUEnsemble

2021-02-19 09:59 UTC, c-yuwei approved these changes

2021-02-19 10:57 UTC, c-yuwei commented on braph2genesis/measures/_DegreeEnsemble.gen.m
> +    'DegreeEnsemble is not being calculated correctly for MultiplexGraphBU.')
...correctly for MultiplexGraphBUEnsemble? or just MultiplexGraphBU

2021-02-19 10:57 UTC, c-yuwei commented on braph2genesis/measures/_DegreeEnsemble.gen.m
> +    'DegreeEnsemble is not being calculated correctly for MultiplexGraphWU.')
same question here ...correctly for MultiplexGraphWUEnsemble? or just MultiplexGraphWU

2021-02-19 11:12 UTC, annacanal commented on braph2genesis/measures/_DegreeEnsemble.gen.m
> +    'DegreeEnsemble is not being calculated correctly for MultiplexGraphBU.')
it should be MultiplexGraphBUEnsemble. ill change it ^^

2021-02-19 11:14 UTC, annacanal approved these changes

2021-02-22 17:23 UTC, merged