global efficency
softmatterlab/Braph-2.0-Matlab pull request #810
Opened 2021-02-18 10:19 UTC by egolol

I'm thinking of putting the ensembles of each here

2021-02-22 19:35 UTC, annacanal requested changes
small details

2021-02-22 19:35 UTC, annacanal commented on braph2genesis/measures/_GlobalEfficiency.gen.m
> +    'GlobalEfficiency is not being calculated correctly for GraphBU.')
GraphWU

2021-02-22 19:35 UTC, annacanal commented on braph2genesis/measures/_GlobalEfficiency.gen.m
> +g = GraphBU('B', B);
this should be GraphWU

2021-02-22 19:35 UTC, annacanal commented on braph2genesis/measures/_GlobalEfficiency.gen.m
> +g = MultiplexGraphBU('B', B);
MultiplexGraphWU or MultiplexGraphBU?

2021-02-22 19:35 UTC, annacanal commented on braph2genesis/measures/_GlobalEfficiency.gen.m
> +    'GlobalEfficiency is not being calculated correctly for MultiplexGraphBU.')
MultiplexGraphWU or MultiplexGraphBU?

2021-02-22 19:35 UTC, annacanal commented on braph2genesis/measures/_GlobalEfficiencyAv.gen.m
> +GraphWU
the title doesnt match the test GraphBU
You could also add at list one test for weighted graphs (from the old measure in braph2)

2021-02-22 19:35 UTC, annacanal commented on braph2genesis/measures/_InGlobalEfficiency.gen.m
> +g = GraphBD('B', B);
same than before.. you just the binary tests. but have Weighted in title

2021-02-22 19:35 UTC, annacanal commented on braph2genesis/measures/_OutGlobalEfficiency.gen.m
> +It is outversely related to the characteristic out-path length.
inversely ?

2021-02-22 19:35 UTC, annacanal commented on braph2genesis/measures/_OutGlobalEfficiency.gen.m
> +GraphWD
same

2021-02-23 13:09 UTC, c-yuwei reviewed
reviewed along with @annacanal 's comments

2021-02-23 18:11 UTC, annacanal approved these changes

2021-02-24 11:41 UTC, giovannivolpe approved these changes

2021-02-24 11:41 UTC, merged