Path length and  in/out strength
softmatterlab/Braph-2.0-Matlab pull request #811
Opened 2021-02-18 14:40 UTC by egolol

- [ ] PathLength, Av

- [ ] IN/OUT - PathLength, Av

- [ ] IN/OUT - Strength, Av

2021-02-22 13:03 UTC, annacanal requested changes
I would add as well test for GraphWU and GraphBU in Path length, and so. since we had them on the version in folder braph2

2021-02-22 13:03 UTC, annacanal commented on braph2genesis/measures/_OutPathLengthAv.gen.m
> +out_path_length = OutPathLengthAv('G', g).get('M');
out_path_length_av

2021-02-22 13:03 UTC, annacanal commented on braph2genesis/measures/_PathLength.gen.m
> +
length*

2021-02-22 13:03 UTC, annacanal commented on braph2genesis/measures/_OutPathLengthAv.gen.m
> +The average out-path length is the average shortest out-path lengths of one
the description is the same of OutPathLength, change

2021-02-22 13:03 UTC, annacanal commented on braph2genesis/measures/_InPathLengthAv.gen.m
> +The average in-path length is the average shortest in-path lengths of one
the description is the same of InPathLength, change

2021-02-22 19:28 UTC, annacanal approved these changes

2021-02-23 13:02 UTC, c-yuwei approved these changes

2021-02-24 11:40 UTC, giovannivolpe requested changes
please, complete definitions of props

2021-02-24 11:40 UTC, giovannivolpe commented on braph2genesis/measures/_InPathLength.gen.m
> +rule (metadata, OPTION)
complete definition of prop

2021-02-25 14:50 UTC, giovannivolpe approved these changes

2021-02-25 14:50 UTC, merged