790 ac in out overlapping strength weighted mpc
softmatterlab/Braph-2.0-Matlab pull request #812
Opened 2021-02-22 08:57 UTC by annacanal

- [ ] average in-strength 
- [ ] average out-strength 
- [ ] in-strength 
- [ ] out-strength 
- [ ] overlapping in-strength 
- [ ] overlapping out-strength 
- [ ] average overlapping in-strength 
- [ ] average overlapping out-strength 
- [ ] weighted multiplex in-participation
- [ ] weighted multiplex out-participation

2021-02-22 11:13 UTC, egolol requested changes

2021-02-22 11:13 UTC, egolol commented on braph2genesis/measures/_InStrength.gen.m
> +A = g.get('A');  % cell array with adjacency matrix
% adjacency matrix (for graph) or 2D-cell array (for multigraph, multiplex, etc.) for all

2021-02-22 12:13 UTC, annacanal commented on braph2genesis/measures/_InStrength.gen.m
> +A = g.get('A');  % cell array with adjacency matrix
% cell with adjacency matrix (for graph) or 2D-cell array (for multigraph, multiplex, etc.) 
maybe better. we can discuss about at the meeting

2021-02-23 12:27 UTC, egolol approved these changes

2021-02-23 13:18 UTC, c-yuwei approved these changes

2021-02-23 17:08 UTC, merged