Richclub, Participation and Richness
softmatterlab/Braph-2.0-Matlab pull request #813
Opened 2021-02-22 14:36 UTC by egolol

- [ ] RichClub, RichClubDegree, RichClubStrength

- [ ] Richness

- [ ] Participation

2021-02-22 15:28 UTC, annacanal reviewed
it fails:
![image](https://user-images.githubusercontent.com/31701548/108729579-fa19c080-752a-11eb-987c-5645fb85b0b0.png)

2021-02-22 15:48 UTC, annacanal requested changes

2021-02-22 15:48 UTC, annacanal commented on braph2genesis/measures/_Radius.gen.m
> +Radius < Measure (m, degree) is the graph degree.
This measure is implemented here: https://github.com/softmatterlab/Braph-2.0-Matlab/pull/798
you can copy from there since it has been reviewed there (like is the graph _radius_ )

2021-02-22 15:48 UTC, annacanal commented on braph2genesis/measures/_RichClub.gen.m
> +    m.set('PARAMETRIC_VALUE', k_level)  % Set the PARAMETRIC_VALUE
you can do this before looping through layers, as you suggested to me.
I think this was wrong

2021-02-22 15:48 UTC, annacanal commented on braph2genesis/measures/_RichClubDegree.gen.m
> +    m.set('PARAMETRIC_VALUE', k_level)  % Set the parameter
same

2021-02-22 15:48 UTC, annacanal commented on braph2genesis/measures/_RichClubDegree.gen.m
> +Connection weights are ignored in calculations.
update description

2021-02-22 15:48 UTC, annacanal commented on braph2genesis/measures/_RichClubStrength.gen.m
> +    m.set('PARAMETRIC_VALUE', s_levels)  % Set the parameter
same

2021-02-22 17:05 UTC, egolol commented on braph2genesis/measures/_Radius.gen.m
> +Radius < Measure (m, degree) is the graph degree.
a then ignore this version.
ill delete it, I tought I clicked on it, that why I did it.

2021-02-22 17:05 UTC, egolol commented on braph2genesis/measures/_RichClub.gen.m
> +    m.set('PARAMETRIC_VALUE', k_level)  % Set the PARAMETRIC_VALUE
I just keept it as it was, did not want to change too much.

2021-02-23 13:31 UTC, c-yuwei requested changes

2021-02-23 13:31 UTC, c-yuwei commented on braph2genesis/measures/_CommunityStructure.gen.m
> +RULES = { ... % vector of triangles rules
might delete it per discussion on 2/22

2021-02-23 13:31 UTC, c-yuwei commented on braph2genesis/measures/_CommunityStructure.gen.m
> +OM_TYPE_OPTIONS = { ...
might delete it per discussion on 2/22

2021-02-23 13:31 UTC, c-yuwei commented on braph2genesis/measures/_CommunityStructure.gen.m
> +rule (metadata, OPTION)
actually, I am still confused if it is metadata here (after checking on the definition...)

2021-02-23 14:58 UTC, egolol commented
They don't pass because they need measures that were not yet implemented for some test cases. Anyway,  I'll update the rule categroy.

2021-02-23 18:30 UTC, annacanal approved these changes

2021-02-23 21:57 UTC, c-yuwei approved these changes

2021-02-24 11:38 UTC, giovannivolpe requested changes
I've started checking the first file. Please polish all:
- use option props correctly
- write definitions of props (ending with point)
- check spaces

2021-02-24 11:38 UTC, giovannivolpe commented on braph2genesis/measures/_CommunityStructure.gen.m
> +
usual comment, make them as option props

2021-02-24 11:38 UTC, giovannivolpe commented on braph2genesis/measures/_CommunityStructure.gen.m
> +[]
not needed, this is the standard default

2021-02-24 11:38 UTC, giovannivolpe commented on braph2genesis/measures/_CommunityStructure.gen.m
> +[]
not noeeded

2021-02-24 11:38 UTC, giovannivolpe commented on braph2genesis/measures/_CommunityStructure.gen.m
> +OM (metadata, MATRIX)
complete all definitions...

2021-02-24 11:48 UTC, annacanal commented
> I've started checking the first file. Please polish all:
> 
> * use option props correctly
> * write definitions of props (ending with point)
> * check spaces

All the changes are for CommunityStrcuture, which is a measure being updated in another branch https://github.com/softmatterlab/Braph-2.0-Matlab/pull/807 (here it is just needed for the calculation of other measures)
so since this is the only measure that needs an updates I would suggest merging this branch

2021-02-24 12:13 UTC, giovannivolpe approved these changes

2021-02-24 12:13 UTC, merged