790 eg kcore edge categoricalpersistance
softmatterlab/Braph-2.0-Matlab pull request #819
Opened 2021-02-25 12:09 UTC by egolol

- [ ] CategoricalPersistence.m
- [ ] EdgeBetweennessCentrality.m
- [ ] EdgeNumberDistance.m
- [ ] EigenvectorCentrality.m
- [ ] KCore.m
- [ ] KCorenessCentrality.m
- [ ] Change Distance

2021-02-26 15:34 UTC, annacanal requested changes

2021-02-26 15:34 UTC, annacanal commented on braph2genesis/measures/_EdgeBetweennessCentrality.gen.m
> +MultiplexWU
We are forgetting the multigraphBUD /BUT (also multiplex BUD/t, but it wont work directly for them)

2021-02-26 15:34 UTC, annacanal commented on braph2genesis/measures/_EdgeBetweennessCentrality.gen.m
> +L = g.layernumber();
N and L arent used later

2021-02-26 15:34 UTC, annacanal commented on braph2genesis/measures/_KCore.gen.m
> +KCore < Measure (m, kcore) is the graph kcore.
KCore < Measure (m, k-core) is the graph k-core.

2021-02-26 15:34 UTC, annacanal commented on braph2genesis/measures/_KCore.gen.m
> +KCoreThreshold (parameter, SCALAR) is the kcore threshold
KCoreThreshold (parameter, SCALAR) is the k-core threshold

2021-02-26 15:34 UTC, annacanal commented on braph2genesis/measures/_KCore.gen.m
> +M (result, cell) is the kcore.
M (result, cell) is the k-core.

2021-02-26 15:34 UTC, annacanal commented on braph2genesis/measures/_KCorenessCentrality.gen.m
> +KCorenessCentrality < Measure (m, kcoreness centrality) is the graph kcoreness centrality.
KCorenessCentrality < Measure (m, k-coreness centrality) is the graph k-coreness centrality.

2021-02-26 15:34 UTC, annacanal commented on braph2genesis/measures/_KCorenessCentrality.gen.m
> +M (result, cell) is the kcoreness centrality.
M (result, cell) is the k-coreness centrality.

2021-02-27 18:31 UTC, egolol commented on braph2genesis/measures/_EdgeBetweennessCentrality.gen.m
> +MultiplexWU
We should later come back to this... so we can change everything one time.

2021-02-27 20:10 UTC, annacanal commented on braph2genesis/measures/_EdgeBetweennessCentrality.gen.m
> +MultiplexWU
yes, maybe once we have all measures in gv-genesis-2 we add these graphs and check everything

2021-02-27 20:12 UTC, annacanal approved these changes

2021-03-01 09:08 UTC, giovannivolpe approved these changes

2021-03-01 09:16 UTC, merged