mex files and measure
softmatterlab/Braph-2.0-Matlab pull request #820
Opened 2021-02-26 11:31 UTC by egolol

2021-02-26 13:52 UTC, annacanal requested changes
The generated MEX files inside private folder need to be in measures folder

2021-03-01 08:20 UTC, annacanal approved these changes

2021-03-01 09:06 UTC, giovannivolpe requested changes
put the MEX files in a subfolder of measures also in the origin

2021-03-01 09:06 UTC, giovannivolpe commented on braph2genesis/genesis/genesis.m
> +disp('¡! copied ready files - measures')
put them in a subfolder of measures also in the origin

2021-03-01 18:48 UTC, merged