Graph nodeattack, edgeattack, subgraphs
softmatterlab/Braph-2.0-Matlab pull request #837
Opened 2021-03-09 15:35 UTC by egolol

Add the following methods to _Graph:

- [x] subgraphs
- [x] nodeattack
- [x] edgeattack
- [x] Updated LocalEfficiency measure

2021-03-15 08:41 UTC, annacanal approved these changes

2021-03-15 08:41 UTC, annacanal commented on braph2genesis/src/gt/_Graph.gen.m
> +        if iscell(A)
isnt 'A' always a cell, now?

2021-03-15 13:17 UTC, egolol commented on braph2genesis/src/gt/_Graph.gen.m
> +        if iscell(A)
that's B no?

2021-03-15 13:29 UTC, annacanal commented on braph2genesis/src/gt/_Graph.gen.m
> +        if iscell(A)
No! B is a matrix for graphs, but A is a cell for all graphs. I have re-checked the graphs

2021-03-17 12:18 UTC, egolol commented on braph2genesis/src/gt/_Graph.gen.m
> +        if iscell(A)
could remove check then.

2021-03-18 08:17 UTC, annacanal approved these changes

2021-03-18 08:42 UTC, giovannivolpe requested changes

2021-03-18 08:42 UTC, giovannivolpe commented on braph2genesis/src/gt/_Graph.gen.m
> +    %  specified nodes are removed from each layer.
not removed, but kept

2021-03-18 08:51 UTC, annacanal commented on braph2genesis/src/gt/_Graph.gen.m
> +    %  specified nodes are removed from each layer.
done

2021-03-18 08:55 UTC, giovannivolpe requested changes

2021-03-18 08:55 UTC, giovannivolpe commented on braph2genesis/src/gt/_Graph.gen.m
> +    %  specified nodes are removed from each layer.
same as before

2021-03-21 06:05 UTC, merged