Fix the warning in DistanceEnsemble
softmatterlab/Braph-2.0-Matlab pull request #858
Opened 2021-04-06 12:45 UTC by c-yuwei

The REASON causing the warning is 

--
Distance want to set the value of 'EDGESNUMBER' which is Category.DATA. 
DATA can only be set when the property is unlocked, but in this case, it is locked as the result is calculated already (line 821-824 in Element.m, line 621-624 in Element.m)
--

PROPOSED SOLUTION is to characterize the 'EDGESNUMBER' as a METADATA, which won't be locked all time.

![image](https://user-images.githubusercontent.com/30530538/113712525-869cce80-96e6-11eb-8026-2811ff719e8d.png)
![image](https://user-images.githubusercontent.com/30530538/113712647-acc26e80-96e6-11eb-80aa-33aa6767e1d5.png)

2021-04-06 15:52 UTC, egolol approved these changes

2021-04-06 18:55 UTC, annacanal approved these changes

2021-04-08 08:50 UTC, giovannivolpe requested changes
I think EDGENUMBER should be a result (not metadata), calculated by calling the fucntion that caculates the distance. If not clear, let's discuss it.

2021-04-19 18:28 UTC, c-yuwei commented
EDGENUMBER has been separated from Distance to EdgeNumberDistance, considering it should be a result rather than metadata.

2021-04-20 11:42 UTC, giovannivolpe approved these changes

2021-04-20 11:42 UTC, merged