1st commit
softmatterlab/Braph-2.0-Matlab pull request #868
Opened 2021-04-10 12:25 UTC by egolol

2021-04-12 13:49 UTC, giovannivolpe commented on braph2genesis/workflows/structural/_AnalyzeGroup_ST_BUT.gen.m
> +
add seealso

2021-04-13 09:38 UTC, annacanal requested changes

2021-04-13 09:39 UTC, annacanal commented on braph2genesis/workflows/structural/example_ST_BUT.m
> +distance_WU_ciu = c_WU.getComparison('Distance').get('CIU');
I did like this in example_BUD. wheter a_BUT1 or a_BUT_1 it is just a preference/taste question hehe

2021-04-13 09:50 UTC, annacanal approved these changes

2021-04-13 10:36 UTC, giovannivolpe approved these changes

2021-04-13 10:36 UTC, merged