889 ac add covariates workflows
softmatterlab/Braph-2.0-Matlab pull request #895
Opened 2021-04-23 13:37 UTC by annacanal

2021-04-26 17:24 UTC, egolol approved these changes

2021-04-27 04:23 UTC, giovannivolpe requested changes
In all exporters, if covariates do not exist, the corresponding file should not be saved.

In all importers, they should also work of the covariate file does not exist.

2021-04-27 04:23 UTC, giovannivolpe commented on braph2genesis/src/analysis/Correlation.m
> +        function [A, P] = getAdjacencyMatrix(data, correlation_rule, negative_weight_rule, covariates)
Give the option to call this function without covariates also.

2021-04-27 04:23 UTC, giovannivolpe commented on braph2genesis/workflows/structural multiplex/_AnalyzeGroup_ST_MP_WU.gen.m
> +            case 'male'
better have male/female as +/-1 and otherwise as 0 (more symmetric for the regression).

2021-04-27 08:34 UTC, annacanal commented on braph2genesis/src/analysis/Correlation.m
> +        function [A, P] = getAdjacencyMatrix(data, correlation_rule, negative_weight_rule, covariates)
it is already possible.

2021-04-27 08:49 UTC, merged