Eg g UI brain atlas final review
softmatterlab/Braph-2.0-Matlab pull request #896
Opened 2021-04-25 19:51 UTC by egolol

2021-04-26 16:02 UTC, annacanal approved these changes

2021-05-05 11:25 UTC, giovannivolpe requested changes
use request close

2021-05-05 12:31 UTC, egolol commented
@giovannivolpe the figure of the surf is not a Plot child so it does not have closerequest, that why I use a listener.

2021-05-06 12:53 UTC, giovannivolpe requested changes

2021-05-06 12:53 UTC, giovannivolpe commented on braph2genesis/genesis/create_Element.m
> -                g(2, ['function ui_menu_export = getGUIMenuExport(' moniker ', f)'])
use moniker

2021-05-06 12:53 UTC, giovannivolpe commented on braph2genesis/src/atlas/_PPBrainAtlasSurf.gen.m
> +
spaces

2021-05-06 12:53 UTC, giovannivolpe commented on braph2genesis/src/atlas/_PlotBrainAtlas.gen.m
> +0
remove

2021-05-06 13:26 UTC, giovannivolpe approved these changes

2021-05-06 13:26 UTC, merged