Eg waiting screen
softmatterlab/Braph-2.0-Matlab pull request #922
Opened 2021-05-10 12:38 UTC by egolol

2021-05-11 07:55 UTC, annacanal reviewed
super nice!
Would be also nice to add a message of: Document exported! or something like that, as we talked :)

2021-05-12 14:22 UTC, giovannivolpe requested changes

2021-05-12 14:22 UTC, giovannivolpe commented on braph2genesis/src/util/change_figure_icon.m
> +    warning('off')
docuemnt

2021-05-12 15:10 UTC, giovannivolpe approved these changes

2021-05-12 15:14 UTC, merged