Eg ensemble measures add params
softmatterlab/Braph-2.0-Matlab pull request #969
Opened 2021-06-21 11:48 UTC by egolol

2021-06-21 13:13 UTC, annacanal reviewed
* When having several parameters in a measure and some are not specified in the set, they are set as 'NoValue', and then the measure does not see that variables empty. Change 'NoValue' for empty
* As we talked, the rules/parameters do not appear from the GUI without doing .set() from command line

2021-06-21 15:48 UTC, egolol commented
> * When having several parameters in a measure and some are not specified in the set, they are set as 'NoValue', and then the measure does not see that variables empty. Change 'NoValue' for empty
> * As we talked, the rules/parameters do not appear from the GUI without doing .set() from command line

Solved

2021-06-21 18:38 UTC, annacanal requested changes
It gives errors when calculating the measure, in the prop checks, when prop = []

2021-06-22 07:48 UTC, annacanal approved these changes

2021-06-22 09:16 UTC, giovannivolpe requested changes

2021-06-22 09:16 UTC, giovannivolpe commented on braph2genesis/measures/_CommunityStructure.gen.m
> +            m.set('quality_function', Q);   % save normalized quality function/modularity
Capitalize property names

2021-06-22 09:20 UTC, annacanal commented on braph2genesis/measures/_CommunityStructure.gen.m
> +            m.set('quality_function', Q);   % save normalized quality function/modularity
Done

2021-06-22 09:25 UTC, giovannivolpe approved these changes

2021-06-22 09:25 UTC, merged